### ISSUE TITLE
"this is not a directory" error when parent is a dfs junction 

### ISSUE THREAD

**Issue by asuffield** [bazelbuild/bazel#11237]
I apologise in advance for the frustratingly hard-to-reproduce nature of this problem.

The observed behaviour is that new_local_repository returns "The repository's path is [...] but this is not a directory.", for a directory which exists and is readily accessible.

The notably odd thing about this directory is that it exists under a DFS path, which shows up very oddly in windows. The path looks something like this:

x:\foo\bar\baz\content.txt

All of these look like regular files, with one exception. If you look at x:\foo itself, you'll find it is reported as a junction to the path "d:\x_drive\foo". However, on the machine where we are running bazel, no such path exists (indeed, no d: volume exists). This is how Windows DFS servers present DFS-mapped paths to clients: the junction point is resolved by the server, and the client sees a junction to an apparently non-existent path, but it seems to work fine.

I have burned a bunch of time on trying to reproduce this behaviour with samba, but it just doesn't do the same thing (samba reports dfs links as directories, not junction points). I suspect it can only be reproduced with multiple windows servers, which isn't something I can readily attach to this bug report.

I believe that this is confounding https://cs.opensource.google/bazel/bazel/+/master:src/main/java/com/google/devtools/build/lib/skyframe/FileFunction.java;l=70?q=FileFunction.compute&ss=bazel with a parent directory that is not a directory, and also is reported as a link to something non-existent, yet still has contents. I acknowledge in advance that this is very frustrating behaviour for a filesystem to have.

**Comment by laszlocsomor** [comment]
The error comes from [`src/main/java/com/google/devtools/build/lib/rules/repository/NewLocalRepositoryFunction.java`](https://cs.opensource.google/bazel/bazel/+/master:src/main/java/com/google/devtools/build/lib/rules/repository/NewLocalRepositoryFunction.java;l=95?q=%22this%20is%20not%20a%20directory%22&ss=bazel%2Fbazel:src%2Fmain%2F)

It passed the earlier existence check. I'm wondering what `dirFileValue` thinks about the junction. Can you attach a debugger to Bazel and peek at it? (Make sure to use the matching sources of your Bazel version.)

**Comment by jackie-h** [comment]
@asuffield and I discussed and I took a look at this on Windows.
After inspecting in the debugger, the issue seems to be that x:\foo is incorrectly identified as a SYMLINK that should be followed here:
https://github.com/bazelbuild/bazel/blob/31b6880c254b099d2e7feb27708b6d52503c6148/src/main/java/com/google/devtools/build/lib/actions/FileStateValue.java#L76
It is identified as a SYMLINK by this:
https://github.com/bazelbuild/bazel/blob/a6deb8b1c6e2a88f8cacd5aaa097452e0b3eddce/src/main/java/com/google/devtools/build/lib/skyframe/PerBuildSyscallCache.java#L119
This directory is a junction rather than a symlink so should not be resolved and followed.
This issue looks as if it is similar to and possibly caused by this:
https://github.com/bazelbuild/bazel/issues/9176
The changes to the WindowsFileSystem on that issue changed the logic to no longer identify x:\foo as a directory, I suspect that is the cause.
It looks as if the logic to treat junctions the same as symlinks would need revising to fix this for DFS.
For this directory:
((sun.nio.fs.WindowsFileAttributes)attributes).isSymbolicLink() is false.
((sun.nio.fs.WindowsFileAttributes)attributes).isDirectory() is true.
((sun.nio.fs.WindowsFileAttributes)attributes).isReparsePoint() is true.
Bazel is treating this directory as a SymbolicLink due to the logic in WindowsFileSystem.fileIsSymbolicLink() which treats junctions and symbolic links as the same.
https://github.com/bazelbuild/bazel/blob/31b6880c254b099d2e7feb27708b6d52503c6148/src/main/java/com/google/devtools/build/lib/windows/WindowsFileSystem.java#L133

Hope that helps with identifying a fix.

**Comment by hicksjoseph** [comment]
@jackie-h @asuffield I was reading this and wondering if you had any suggested fix that you would like to propose.

**Comment by laurentlb** [comment]
cc @meteorcloudy

**Comment by asuffield** [comment]
I haven't quite wrapped my head around it in enough detail - there's clearly a mistake in here about considering junctions and symlinks to be the same, and I think I can assemble a description of the correct way to interpret junctions (which is surprising and annoying, but is also how they work): a realpath()-like function should resolve junctions only when they are on a local ntfs filesystem, and treat them as regular directories in all other cases.

Mapping that concept into bazel's filesystem handling would require some careful thinking.

**Comment by meteorcloudy** [comment]
Sounds like we should treat dfs junction as regular directory in Bazel?
If so, we can fix this function
https://github.com/bazelbuild/bazel/blob/cffd417a4c4ec4d082f815f57a771ad1010972dd/src/main/native/windows/file.cc#L74-L101

We can probably tell the junction type differences by checking the reparse point tags:
https://docs.microsoft.com/en-us/windows/win32/fileio/reparse-point-tags

**Comment by laszlocsomor** [comment]
> We can probably tell the junction type differences by checking the reparse point tags:
> https://docs.microsoft.com/en-us/windows/win32/fileio/reparse-point-tags

Certainly.  `ReadSymlinkOrJunction` does that already:
https://github.com/bazelbuild/bazel/blob/cffd417a4c4ec4d082f815f57a771ad1010972dd/src/main/native/windows/file.cc#L510

**Comment by asuffield** [comment]
I don't actually know if this would work, but should ReadSymlinkOrJunction just ignore junctions which are not on NTFS filesystems? The bizarre underlying behaviour is that junctions are evaluated in the NTFS driver, so the path in them can only be followed on the machine where NTFS is running; on any network filesystem, the content is effectively opaque.

**Comment by meteorcloudy** [comment]
>  but should ReadSymlinkOrJunction just ignore junctions which are not on NTFS filesystems? 

I think there are two solution here:

1. We change `IsSymlinkOrJunction` to only recognize reparse point tagged as `IO_REPARSE_TAG_SYMLINK` and `IO_REPARSE_TAG_MOUNT_POINT`. Then, we can ensure `ReadSymlinkOrJunction` will always have a solution.

2. In `ReadSymlinkOrJunction`, we don't return `kUnknownLinkType` if the reparse tag is not recognized, just return the original path as resolved path. But I think this is against the meaning of the function name `ReadSymlinkOrJunction`.

I would perfer the first solution, WDYT?

**Comment by asuffield** [comment]
I don't think I have a strongly held opinion on this topic, beyond irritation at the byzantine behaviour here.

I can easily test a change (since it's rather tedious to set this up - I don't have a reproduction case which doesn't include a Windows DFS server)

**Comment by meteorcloudy** [comment]
OK, I have implemented a fix in https://github.com/bazelbuild/bazel/commits/gh_11237_fix_on_3.3.1, based on Bazel 3.3.1.

You can download a prebuilt Bazel binary with this fix at:
https://storage.googleapis.com/bazel-builds/artifacts/windows/c728b71c06dc8da4cb47385bcd7448bdffaa8b3c/bazel
(Rename to bazel.exe)

Can you test if this fix the problem?

**Comment by meteorcloudy** [comment]
Ping @asuffield, did you have a chance to take a look? 😃

**Comment by asuffield** [comment]
No better - and I dig a little debugging in that function to find out why. The offending junction point is reported as IO_REPARSE_TAG_MOUNT_POINT on the windows client.

**Comment by meteorcloudy** [comment]
That's weird, and it's not tagged as `IO_REPARSE_TAG_DFS` I assume?

**Comment by meteorcloudy** [comment]
@asuffield Can you help find out the difference between a DFS junction and a regular junction?

**Comment by meteorcloudy** [comment]
Also I found a bug in my attempted fix https://github.com/bazelbuild/bazel/commit/c728b71c06dc8da4cb47385bcd7448bdffaa8b3c
It should be `find_file_data.dwReserved0 == IO_REPARSE_TAG_SYMLINK` instead of `find_file_data.dwReserved0 & IO_REPARSE_TAG_SYMLINK`

**Comment by meteorcloudy** [comment]
I fixed the bug, can you try again with
https://storage.googleapis.com/bazel-builds/artifacts/windows/ccf842e0baa9ee354b5c83c6c940e2210fe4a6f7/bazel ?

**Comment by asuffield** [comment]
Exact values are dwFileAttributes == 0x410, dwReserved0 == 0xa0000003. No luck there, it looks like any other junction.

I am currently slightly puzzled by how we are supposed to interact with junctions in the Windows API, although not very surprised by this.

We might have to inspect the filesystem where it's located to find out if that's local or remote.

(I have to rebuild the binary with our own patch set to test it, but I'll run that change through just to check - but given the above, I don't expect it to help)

**Comment by asuffield** [comment]
I'm not sure if this is universally correct, but based on how I understand this working: https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-getdrivetypea will be DRIVE_FIXED for any volume on which we can interpret IO_REPARSE_TAG_MOUNT_POINT, and DRIVE_REMOTE for volumes on which the remote server interprets it for us. I'm not sure what happens for the other values, but I suspect the answer is they never support reparse points.

I am curious what GetVolumeInformationA says about FILE_SUPPORTS_REPARSE_POINTS, will have to check that.

**Comment by philwo** [comment]
@asuffield @meteorcloudy What's the state of this issue?

**Comment by asuffield** [comment]
Still unsolved, and still a problem. I've not had time to go chase this cluster of problems yet, but we will need to solve it somehow.
