### ISSUE TITLE
Downstream projects are broken by Bazel <-> rules_apple incompatibilities

### ISSUE THREAD

**Issue by fweikert** [bazelbuild/bazel#13811]
Several downstream projects are broken due to two different Bazel changes that are incompatible with older versions of rules_apple:

`target 'StdRedirect.dylib' not declared in package 'tools/objc'` caused by https://github.com/bazelbuild/bazel/commit/67586a2a02d94bd1dde004fce46abc7595c0cca2 (**June 8th**).
Impacted projects:

- Bazel Examples: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/2124#12f494ce-91ec-484b-b95d-de1d8ce7630f
- Tulsi: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/2129#4af84457-5ca9-4fe5-b3db-fe9d5b1201e1 (https://github.com/bazelbuild/tulsi/issues/258)

`'apple_common' value has no field or method 'objc_proto_aspect'` caused by https://github.com/bazelbuild/bazel/commit/d6830672311d54c8072e0b48c440c2edde65314d (**May 3rd**).
Impacted projects:

- TensorFlow: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/2124#4354d0da-1f54-4389-81cf-d1ccce0b6bea
- FlatBuffers: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/2129#1a2475cc-c60f-4ecd-aa4c-764a7386bbb0

rules_apple itself passes all tests with Bazel-at-HEAD, which means that the aforementioned projects should update their version of rules_apple. Unfortunately this isn't trivial since they are stuck at older Bazel versions (3.7.*).

**Comment by keith** [comment]
Examples fixed here https://github.com/bazelbuild/examples/pull/217

Re-enabled here: https://github.com/bazelbuild/continuous-integration/pull/1199

**Comment by keith** [comment]
Tulsi fixed here: https://github.com/bazelbuild/tulsi/pull/268

Re-enabled here: https://github.com/bazelbuild/continuous-integration/pull/1200

**Comment by keith** [comment]
Here's an attempt at updating the rules in grpc, which could then be updated in flatbuffers https://github.com/grpc/grpc/pull/26941

**Comment by sventiffe** [comment]
This issue did not receive an update for a while. @fweikert do we still consider this a P1 and if so please update

**Comment by wookayin** [comment]
Any updates on this? This breaks many downstream projects.

**Comment by keith** [comment]
Which projects are you specifically talking about now? Most of these were fixed by updating the rules since they have to be updated over time as bazel is.

**Comment by wookayin** [comment]
@keith [reverb](https://github.com/deepmind/reverb/) and [jax](https://github.com/google/jax/issues/8440). I see the exact same error with bazel 6.x.x -- I could raise an issue there, but is it just a matter of simply updating the rule file? How exactly? I didn't see any version modifier in the build configuration.

This is what I see in `WORKSPACE`:
```
load(
    "@build_bazel_rules_apple//apple:repositories.bzl",
    "apple_rules_dependencies",
)

apple_rules_dependencies()
```

**Comment by keith** [comment]
It depends on your project where the version is defined. Which project are you working on? Somewhere there should be an http_archive rule for rules_apple that encodes the version.

**Comment by wookayin** [comment]
@keith As I said, reverb and jax. A few questions for you:

Following your suggestion, I've added the following `http_archive` rule in the `WORKSPACE` file

```diff
+http_archive(
+    name = "build_bazel_rules_apple",
+    sha256 = "0052d452af7742c8f3a4e0929763388a66403de363775db7e90adecb2ba4944b",
+    urls = [
+        "https://github.com/bazelbuild/rules_apple/releases/download/0.31.3/rules_apple.0.31.3.tar.gz",
+    ],
+)
 
 load(
     "@build_bazel_rules_apple//apple:repositories.bzl",
     "apple_rules_dependencies",
 )
```

but when I am building with bazel I still see the error `Error: 'apple_common' value has no field or method 'objc_proto_aspect'` The referenced `build_bazel_rules_apple/apple/internal/rule_factory.bzl` seems outdated (not following the 0.31.3 version). I also tried cleaning up `~/.cache/bazel`. How can this happen?

I tried this on two setups I have; one on macOS and another on Linux x86_64. With the same code, one worked (the build goes through) but one fails with the above error. Both had bazel 6.0.0-pre.20211215.3, so it should be probably only me who have some configs/caches issues but I cannot get what's going on here.

Also, if no http_archive rule is defined, isn't it supposed to fetch the latest version/release from `bazelbuild/rules_apple`? Maybe other dependencies in [WORKSPACE](https://github.com/deepmind/reverb/blob/master/WORKSPACE) are stilling pinning to an old version?

**Comment by meteorcloudy** [comment]
All failing projects are fixed now

**Comment by dbaileychess** [comment]
This seems to be hitting us again at Flatbuffers: https://github.com/google/flatbuffers/issues/7029 Recent PRs are starting to fail and I couldn't find any local code changes. 

Here is our [WORKSPACE](https://github.com/google/flatbuffers/blob/master/WORKSPACE#L5) file.

**Comment by meteorcloudy** [comment]
@dbaileychess You'll have to upgrade grpc to version v1.42.0 or later. See the release note here: https://github.com/grpc/grpc/releases/tag/v1.42.0

**Comment by dbaileychess** [comment]
@meteorcloudy Thanks, i updated to 1.42 and it is green.
