### ISSUE TITLE
ObjC rules are no longer appearing in the sidebar

### ISSUE THREAD

**Issue by kchodorow** [bazelbuild/bazel#1615]
http://www.bazel.io/docs/be/objective-c.html is still available, but doesn't appear under Build Encyclopedia -> Rules.

**Comment by davidzchen** [comment]
I just returned from vacation. I'll take a look at this now.

**Comment by davidzchen** [comment]
Actually, I found that bringing up a local instance of the site (using both the internal and external `serve-docs` script) at HEAD still has the Objective-C rules link on the sidebar. I'm not sure why the last site push removed the link. Can we try doing another push to see whether the objc rules are restored? If not, I'll investigate further.

**Comment by davidzchen** [comment]
This has been fixed by the latest site push.

**Comment by jhfield** [comment]
I dopn't see the Objective-C rules link in the sidebar you get to when you click on the main "Docs" link (i.e., https://www.bazel.io/versions/master/docs/install.html, expand "Rules"). So something still appears to be broken.

**Comment by bolinfest** [comment]
I don't see it either and I hit cmd-shift-r to force reload.

**Comment by davidzchen** [comment]
I am able to reproduce this now. Oddly, it seems that this is caused by the docgen reporting that the objc rules are undocumented:

```
INFO: From Executing genrule //src/main/java/com/google/devtools/build/lib:gen_buildencyclopedia:
WARNING: The following rules are undocumented: [android_ndk_repository, android_sdk, android_sdk_repository, android_tools_defaults_jar, apple_binary, apple_cc_toolchain, apple_watch1_extension, apple_watch2_extension, apple_watch_extension_binary, cc_toolchain, cc_toolchain_suite, environment, experimental_objc_library, genquery, ios_application, ios_device, ios_extension, ios_extension_binary, ios_framework, ios_framework_binary, ios_test, j2objc_library, objc_binary, objc_bundle, objc_bundle_library, objc_framework, objc_import, objc_library, objc_proto_library, objc_xcodeproj, xcode_config, xcode_version]
```

**Comment by davidzchen** [comment]
I found the root cause. The problem was that the Java source files for the Obj-C rules, as well as some Apple rules and `genquery`, were not added to `//src/main/java/com/google/devtools/build/lib:docs_embedded_in_sources` since the packages that those source files live in have their own BUILD files.

**Comment by bolinfest** [comment]
Is this still waiting for a site push? I don't see the fix live yet.

**Comment by jhfield** [comment]
Looks ok to me now, e.g., I see the Objective-C link from the sidebar here: https://bazel.io/versions/master/docs/install.html.

**Comment by bolinfest** [comment]
@jhfield Ah, thanks, I see it now. I don't know if this is by design or not, but the list is not sorted alphabetically, so I missed it.

Is it me, or was it properly sorted before?

**Comment by davidzchen** [comment]
I don't think it was ever sorted, and we have more or less have always had this ordering. I can see how it might appear a bit strange since we first list all the native rule families then the Skylark rules, but in the future, we would like to set up a registry for finding Skylark rules (see #1046).
