### ISSUE TITLE
Windows, tests: missing toolchain while testing //src/test/j/c/g/devtools/build/lib:*

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#1736]
Example:

```
1) isStrictDepsJavaProtoLibrary_flagIsFalse_noPackageLevelAttribute(com.google.devtools.build.lib.rules.java.proto.StrictDepsUtilsTest)
com.google.devtools.build.lib.analysis.config.InvalidConfigurationException: cc_toolchain_suite '@bazel_tools//tools/cpp:toolchain' does not contain a toolchain for CPU 'x64_windows' and compiler 'windows_msys64'
        at com.google.devtools.build.lib.rules.cpp.CppConfigurationLoader.createParameters(CppConfigurationLoader.java:186)
        at com.google.devtools.build.lib.rules.cpp.CppConfigurationLoader.create(CppConfigurationLoader.java:72)
        at com.google.devtools.build.lib.rules.cpp.CppConfigurationLoader.create(CppConfigurationLoader.java:47)
        at com.google.devtools.build.lib.skyframe.ConfigurationFragmentFunction.compute(ConfigurationFragmentFunction.java:77)
        at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:387)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:496)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by laszlocsomor** [comment]
Found in https://github.com/bazelbuild/bazel/issues/1735

**Comment by kchodorow** [comment]
LMK if/when you want me to push.

**Comment by laszlocsomor** [comment]
I strongly suspect that I introduced the breakages with https://github.com/bazelbuild/bazel/commit/4a249b6962d32ed4cfd4165dfdae4a555b00bb69.

If you want to push, I think it's OK to do so any time, given that the commit is already pushed. I treat this with high priority still.

**Comment by kchodorow** [comment]
No, @hermione521 already pushed today, so I'll only push again if we have fixed someting.

**Comment by meteorcloudy** [comment]
I suspect it's introduce by 0d32fc88d6d179bedef4a04bc22c44583365b859, I also got this error after I fixed #1732

**Comment by meteorcloudy** [comment]
On windows, we are still using [BUILD.static](https://github.com/bazelbuild/bazel/blob/master/tools/cpp/BUILD.static#L28) in [cc_configure.bzl,](https://github.com/bazelbuild/bazel/blob/master/tools/cpp/cc_configure.bzl#L435) we should modify BUILD.static to adapt 0d32fc8. I think I can fix it.

**Comment by meteorcloudy** [comment]
It seems my change only fixed bootstrap but didn't fix the test. Reopen it.
