### ISSUE TITLE
Incompatible targets with selects on a label flag config produce spurious "is not a valid select() condition" errors, are not skipped

### ISSUE THREAD

**Issue by tpudlik** [bazelbuild/bazel#23003]
### Description of the bug:

A target with a `select` statement referencing a `config_setting` based on a `label_flag` will not be correctly detected as incompatible with the target platform. Instead, you get the message `<config setting> is not a valid select() condition for //:library_with_select`.

This is particularly severe because it breaks incompatible target skipping. Instead of skipping the incompatible target, Bazel prints the error message above.

This bug is a little hard to understand based on this description, but it's easy to reproduce. See https://github.com/tpudlik/not_a_valid_select for a simple `BUILD.bazel` file and repro steps.

### Which category does this issue belong to?

Configurability

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

https://github.com/tpudlik/not_a_valid_select

### Which operating system are you running Bazel on?

Linux

### What is the output of `bazel info release`?

release 8.0.0-pre.20240618.2

### If this is a regression, please try to identify the Bazel commit where the bug was introduced with bazelisk --bisect.

I don't believe this ever worked. I get the same error on Bazel 7.2.1, too.

### Any other information, logs, or outputs that you want to share?

This bug may sound a little academic, but it's not! We've run into this in a real project (http://pwrev.dev/221036).

**Comment by tpudlik** [comment]
@katre FYI

**Comment by katre** [comment]
Also @gregestren and @AustinSchuh

**Comment by gregestren** [comment]
Weird. It's got to be something with `label_flag` acting alias-like and somehow not propagating the right info.

I'll dig in and diagnose.

**Comment by gregestren** [comment]
@aranguyen is looking now.

**Comment by aranguyen** [comment]
Hi all, the error is being thrown [here](https://github.com/bazelbuild/bazel/blob/bcb821831a16ce9d3d59b92f7a62e9b6fe188335/src/main/java/com/google/devtools/build/lib/analysis/producers/ConfigConditionsProducer.java#L157) due to [null](https://github.com/bazelbuild/bazel/blob/bcb821831a16ce9d3d59b92f7a62e9b6fe188335/src/main/java/com/google/devtools/build/lib/analysis/config/ConfigConditions.java#L67) ConfigMatchingProvider from `ConfiguredTarget.getProvider(ConfigMatchingProvider.class)`

The `ConfiguredTarget` is being produced by `ConfiguredTargetAndDataProducer` which has been noted to possibly produced a [different configuration](https://github.com/bazelbuild/bazel/blob/bcb821831a16ce9d3d59b92f7a62e9b6fe188335/src/main/java/com/google/devtools/build/lib/analysis/producers/ConfiguredTargetAndDataProducer.java#L39) for alias. And Bazel treats`label_flag` as an alias. In addition, the current implementation of `ConfigSettings` probably also needs modification to work with `label_flag`. Tracing back to a few previous release, this issue was also observed.

For immediate usage, please use `constraint_setting` as a workaround. I will lower the priority of this issue but we're planning to pick them up in the future as this seems to be an oversight and there aren't obvious reason why `label_flag` can't be used with `config_setting`.

**Comment by gregestren** [comment]
From https://github.com/tpudlik/not_a_valid_select:

> This is caused by lines 35--35 in BUILD.bazel:
>
>   includes = select({
>      ":flag_points_to_a": [],
 >     "//conditions:default": ["public"],
>    }),
>
> These lines are in fact correct, and would work fine if the deps of library_with_select did not include an incompatible target.

The example has two references to the incompatible setting:

1. `deps = [":label_flag"]`
2. `select(":flag_points_to_a": [], ...)`

Are you saying that 1. is the only reason building `library_with_select` should fail? And that 2 should properly resolve, as `--//label_flag=a` is a valid `flag=value` pair even though the underlying CT that flag references is incompatible?

**Comment by gregestren** [comment]
I hope https://github.com/bazelbuild/bazel/pull/24542 addresses this but appreciate verification since there are so many subtleties  on the interoperation of `config_setting` / `label_flag` / aliases / target skipping.

I'm sure some of that interoperation still doesn't make sense. I'm hoping https://github.com/bazelbuild/bazel/pull/24542 incrementally moves forward and unblocks current user pain.

**Comment by tpudlik** [comment]
The PR looks reasonable to me, and I verified that it fixes the repro in https://github.com/tpudlik/not_a_valid_select. Nice! Thank you for digging into this!

I tried quickly verifying that this works in actual production examples. (Specifically, we'd like to use `config_setting`s based on `label_flag`s to retire some manually-managed `constraint_value`s like [this one](https://cs.opensource.google/pigweed/pigweed/+/main:pw_unit_test/BUILD.bazel;l=65-78;drc=8b4ba86bf9f58c61d94cb19f04bd931f100d9886) or [this one](https://cs.opensource.google/pigweed/pigweed/+/main:pw_cpu_exception/BUILD.bazel;l=89-95;drc=8b4ba86bf9f58c61d94cb19f04bd931f100d9886)). Unfortunately, there have been a bunch of non-backwards-compatible changes to Bazel since the version we're on currently (https://github.com/bazelbuild/bazel/commit/1ff5af18d045e8f30a2a0367470db4e8225a785c), so getting Pigweed to build with https://github.com/bazelbuild/bazel/commit/916e8581bb2861838fbec0cb6e9228caac7efddc will be a bit of a project. Filed https://pwbug.dev/382324461 to track it.

**Comment by afoxley** [comment]
I can also confirm https://github.com/bazelbuild/bazel/commit/916e8581bb2861838fbec0cb6e9228caac7efddc fixes the issue for me as well, but it looks like this didn't make it into any release yet. Is there any way for it to make it into a Bazel 8 bugfix release?

**Comment by fmeum** [comment]
@bazel-io fork 8.1.0

**Comment by iancha1992** [comment]
A fix for this issue has been included in [Bazel 8.1.0 RC1](https://github.com/bazelbuild/bazel/releases/tag/8.1.0rc1). Please test out the release candidate and report any issues as soon as possible.
If you're using Bazelisk, you can point to the latest RC by setting USE_BAZEL_VERSION=8.1.0rc1. Thanks!

**Comment by afoxley** [comment]
Tested 8.1.0rc1 and my repro case has been fixed, thanks!

**Comment by tpudlik** [comment]
I now successfully tested this in my actual use as well (http://pwrev.dev/268812). Thank you for the fix!

**Comment by sthornington** [comment]
Mentioned on the patch thread, could this be back-ported to 7.6?

**Comment by iancha1992** [comment]
@bazel-io fork 7.7.0

**Comment by sthornington** [comment]
Thank you - I tried a build from the `release-7.7.0` branch, and though the error message is better, it has not solved my problem trying to upgrade our cc toolchains and build abseil (as part of a transitive dependency).

```
ERROR: /scratch/simont/bazel_base/0faca2fc49274d43fb8458c03d751cba/external/com_google_absl/absl/BUILD.bazel:23:15: in flag_values attribute of config_setting rule @@com_google_absl//absl:clang_compiler: error while parsing user-defined configuration values: flag_values keys must be build settings or feature flags and @@bazel_tools//tools/cpp:compiler is not
ERROR: /scratch/simont/bazel_base/0faca2fc49274d43fb8458c03d751cba/external/com_google_absl/absl/BUILD.bazel:23:15: Analysis of target '@@com_google_absl//absl:clang_compiler' failed
ERROR: /scratch/simont/bazel_base/0faca2fc49274d43fb8458c03d751cba/external/com_google_absl/absl/types/BUILD.bazel:224:11: errors encountered resolving select() keys for @@com_google_absl//absl/types:variant
```
I'll leave this here for now in case it looks familiar to anyone!

**Comment by gregestren** [comment]
Hey @sthornington . That passes for me in a simple workspace:

```sh
$ cat MODULE.bazel
bazel_dep(name = "abseil-cpp", version = "20250814.1")

$ custom_built_bazel version
Build label: 7.7.0

$ custom_built_bazel build @abseil-cpp//absl:clang_compiler
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
```

I'm happy to help diagnose further if you can clarify the reproduction.

**Comment by sthornington** [comment]
I reimplemented my toolchains from scratch and they are working now, so I am not sure what the issue was...

**Comment by iancha1992** [comment]
A fix for this issue has been included in [Bazel 7.7.0 RC1](https://github.com/bazelbuild/bazel/releases/tag/7.7.0rc1). Please test out the release candidate and report any issues as soon as possible.
If you're using Bazelisk, you can point to the latest RC by setting USE_BAZEL_VERSION=7.7.0rc1. Thanks!
