### ISSUE TITLE
Specifying --output_base to something under /tmp does not work

### ISSUE THREAD

**Issue by kush-c** [bazelbuild/bazel#2686]
This passes: bazel //src/test/shell/bazel:bazel_example_test
This fails: bazel --output_base=/tmp/bazelhead/usr/local/google/home/kush/bzlclean test //src/test/shell/bazel:bazel_example_test

(This is true for other integration tests as well)

I see errors of the form:
src/main/tools/linux-sandbox-pid1.cc:257: "mount(/tmp/testbazel/usr/local/google/home/kush/bzlclean/bazel-sandbox/0c3169c3-1a84-44f3-a01d-1ed523219dea-950/execroot/bzlclean/_tmp/bazel_example_test_1/workspace, tmp/testbazel/usr/local/google/home/kush/bzlclean/bazel-sandbox/0c3169c3-1a84-44f3-a01d-1ed523219dea-950/execroot/bzlclean/_tmp/bazel_example_test_1/workspace, NULL, MS_BIND, NULL)": No such file or directory

### Environment info
* Operating System:
Ubuntu-linux 64 bit

* Bazel version (output of `bazel info release`):
0.4.4

**Comment by ulfjack** [comment]
IIRC, output base can't be under /tmp. There's probably a bug for this already.

**Comment by aj-michael** [comment]
I believe the bug was #1882 but that was supposedly fixed by @philwo in 52f4e8bbaf18ea489acd2db464f267757e8eb6d4.

**Comment by kush-c** [comment]
Yup. changing the output_base to something other than /tmp fixed the problem.

#1882 dealt with blaze not working well when running inside /tmp, which was fixed. But specifying the --output_base to something under /tmp still fails.

I couldn't find another bug in the internal list or out here, so keeping this open.

**Comment by nfelt** [comment]
My team ran into this bug - it actually does affect building with a workspace under /tmp as well.  I was actually about to file a new issue for that when I found that one.  Maybe we can update the title of this issue to mention that it also affects the workspace?  Would have helped me find this.

I believe the issue affects 0.4.4 and 0.4.5 and is the result of a regression introduced by 18e6b41 ("Add customized path mounting in Bazel sandbox.").  The original issue #1882 was fixed in 52f4e8b by automatically mounting the workspace and output base within the sandbox if they were originally under /tmp (since I guess the tmpfs mount was otherwise overwriting them).

The problem is that 18e6b41 changes the bind mount functionality in `linux-sandbox-pid1.cc` `MountFilesystems()` to remove the `CreateTarget()` call before doing the mount:
https://github.com/bazelbuild/bazel/commit/18e6b410a7f4e24b67740978d101cd665edea6cc#diff-275e01ad7065312d0e325fd7d27709c3L260

This appears to be intentional based on comment history in https://bazel-review.googlesource.com/#/c/7150/ and logic added in 18e6b41 to validate that all bind mount targets specified by the `--sandbox_add_mount_pair` flag must have pre-existing targets:
https://github.com/bazelbuild/bazel/commit/18e6b410a7f4e24b67740978d101cd665edea6cc#diff-29a0529516713be5d80d916b59d015bcR217

However, that logic skips over the two bind mount pairs that are automatically added by `LinuxSandboxedStrategy.getReadOnlyBindMounts()` for the workspace and output base if they are under `/tmp`, which was the fix introduced by 52f4e8b:
https://github.com/bazelbuild/bazel/commit/18e6b410a7f4e24b67740978d101cd665edea6cc#diff-29a0529516713be5d80d916b59d015bcL181

So these two bind mount pairs are left without a target, and hence can't be created.

Note that in addition, this also affects the use of the `--sandbox_add_mount_pair` flag itself with paths under /tmp.

Here's a repro case I did using a Google Cloud Shell VM (Debian 8):
```
~$ sudo update-java-alternatives -s java-1.8.0-openjdk-amd64
~$ export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-amd64
~$ bazel version
Build label: 0.4.5
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Mar 16 12:19:38 2017 (1489666778)
Build timestamp: 1489666778
Build timestamp as int: 1489666778
```

Failure case for workspace under /tmp:
```
~$ cd /tmp
/tmp$ mkdir test-workspace && cd test-workspace
/tmp/test-workspace$ touch WORKSPACE
/tmp/test-workspace$ echo 'cc_binary(name = "hello", srcs = ["hello.c"],)' > BUILD
/tmp/test-workspace$ echo 'int main() { printf("Hello\n"); return 0; }' > hello.c
/tmp/test-workspace$ bazel build --verbose_failures --sandbox_debug //:hello
....................
INFO: Found 1 target...
ERROR: /tmp/test-workspace/BUILD:1:1: C++ compilation of rule '//:hello' failed: linux-sandbox failed: error executing command
 
  (exec env - \
  /home/nickfelt/.cache/bazel/_bazel_nickfelt/ee1fd4cc98721a5d6305f53e534bc4d4/execroot/test-workspace/_bin/linux-sandbox @/ho
me/nickfelt/.cache/bazel/_bazel_nickfelt/ee1fd4cc98721a5d6305f53e534bc4d4/bazel-sandbox/193884d7-1384-45e5-9d97-a0d304b9d2ec-0
/linux-sandbox.params -- /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -B/usr/bin -B/usr/bin -Wunused-but-set-paramet
er -Wno-free-nonheap-object -fno-omit-frame-pointer -MD -MF bazel-out/local-fastbuild/bin/_objs/hello/hello.pic.d -fPIC -iquot
e . -iquote bazel-out/local-fastbuild/genfiles -iquote external/bazel_tools -iquote bazel-out/local-fastbuild/genfiles/externa
l/bazel_tools -isystem external/bazel_tools/tools/cpp/gcc3 -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DAT
E__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c hello.c -o bazel-out/local-fastbuild/bin/_objs/hello/h
ello.pic.o).
src/main/tools/linux-sandbox.cc:186: linux-sandbox-pid1 has PID 2472
src/main/tools/linux-sandbox-pid1.cc:233: tmpfs: /tmp
src/main/tools/linux-sandbox-pid1.cc:243: working dir: /home/nickfelt/.cache/bazel/_bazel_nickfelt/ee1fd4cc98721a5d6305f53e534
bc4d4/bazel-sandbox/193884d7-1384-45e5-9d97-a0d304b9d2ec-0/execroot/test-workspace
src/main/tools/linux-sandbox-pid1.cc:244: sandbox root: /home/nickfelt/.cache/bazel/_bazel_nickfelt/ee1fd4cc98721a5d6305f53e53
4bc4d4/bazel-sandbox/193884d7-1384-45e5-9d97-a0d304b9d2ec-0/tmp
src/main/tools/linux-sandbox-pid1.cc:173: CreateTarget(home/nickfelt/.cache/bazel/_bazel_nickfelt/ee1fd4cc98721a5d6305f53e534b
c4d4/bazel-sandbox/193884d7-1384-45e5-9d97-a0d304b9d2ec-0/execroot/test-workspace, true)
src/main/tools/linux-sandbox-pid1.cc:255: bind mount: /tmp/test-workspace -> /tmp/test-workspace
src/main/tools/linux-sandbox-pid1.cc:257: "mount(/tmp/test-workspace, tmp/test-workspace, NULL, MS_BIND, NULL)": No such file 
or directory
src/main/tools/linux-sandbox.cc:226: child exited normally with exitcode 1
Use --strategy=CppCompile=standalone to disable sandboxing for the failing actions.
Target //:hello failed to build
INFO: Elapsed time: 8.656s, Critical Path: 0.32s
```

Contents of `linux-sandbox.params`:
```
/tmp/test-workspace$ cat /home/nickfelt/.cache/bazel/_bazel_nickfelt/ee1fd4cc98721a5d6305f53e53
4bc4d4/bazel-sandbox/193884d7-1384-45e5-9d97-a0d304b9d2ec-0/linux-sandbox.params 
-D
-S
/home/nickfelt/.cache/bazel/_bazel_nickfelt/ee1fd4cc98721a5d6305f53e534bc4d4/bazel-sandbox/193884d7-1384-45e5-9d97-a0d304b9d2e
c-0/tmp
-W
/home/nickfelt/.cache/bazel/_bazel_nickfelt/ee1fd4cc98721a5d6305f53e534bc4d4/bazel-sandbox/193884d7-1384-45e5-9d97-a0d304b9d2e
c-0/execroot/test-workspace
-M
/tmp/test-workspace
```

Failure case for `--sandbox_add_mount_pair`:
```
~/test-workspace$ mkdir /tmp/foo && echo "Hello" > /tmp/foo/hello.txt
~/test-workspace$ bazel build --verbose_failures --sandbox_debug --sandbox_add_mount_pair=/tmp/foo:/tmp/foo //:hello
INFO: Found 1 target...
ERROR: /home/nickfelt/test-workspace/BUILD:1:1: C++ compilation of rule '//:hello' failed: linux-sandbox failed: error executing command 
  (exec env - \
  /home/nickfelt/.cache/bazel/_bazel_nickfelt/20051cc559686f7b930c594e41661f13/execroot/test-workspace/_bin/linux-sandbox @/home/nickfelt/.cache/bazel/_bazel_nickfelt/20051c
c559686f7b930c594e41661f13/bazel-sandbox/e4dfdadb-2350-49f8-bd3d-d6d954fa88cc-0/linux-sandbox.params -- /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -B/usr/bin -B/
usr/bin -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -MD -MF bazel-out/local-fastbuild/bin/_objs/hello/hello.pic.d -fPIC -iquote . -iquote baz
el-out/local-fastbuild/genfiles -iquote external/bazel_tools -iquote bazel-out/local-fastbuild/genfiles/external/bazel_tools -isystem external/bazel_tools/tools/cpp/gcc3 -fn
o-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c hello.c -o bazel-out/local-fastbuild/
bin/_objs/hello/hello.pic.o).
src/main/tools/linux-sandbox.cc:186: linux-sandbox-pid1 has PID 4281
src/main/tools/linux-sandbox-pid1.cc:233: tmpfs: /tmp
src/main/tools/linux-sandbox-pid1.cc:243: working dir: /home/nickfelt/.cache/bazel/_bazel_nickfelt/20051cc559686f7b930c594e41661f13/bazel-sandbox/e4dfdadb-2350-49f8-bd3d-d6d
954fa88cc-0/execroot/test-workspace
src/main/tools/linux-sandbox-pid1.cc:244: sandbox root: /home/nickfelt/.cache/bazel/_bazel_nickfelt/20051cc559686f7b930c594e41661f13/bazel-sandbox/e4dfdadb-2350-49f8-bd3d-d6
d954fa88cc-0/tmp
src/main/tools/linux-sandbox-pid1.cc:173: CreateTarget(home/nickfelt/.cache/bazel/_bazel_nickfelt/20051cc559686f7b930c594e41661f13/bazel-sandbox/e4dfdadb-2350-49f8-bd3d-d6d9
54fa88cc-0/execroot/test-workspace, true)
src/main/tools/linux-sandbox-pid1.cc:255: bind mount: /tmp/foo -> /tmp/foo
src/main/tools/linux-sandbox-pid1.cc:257: "mount(/tmp/foo, tmp/foo, NULL, MS_BIND, NULL)": No such file or directory
src/main/tools/linux-sandbox.cc:226: child exited normally with exitcode 1
Use --strategy=CppCompile=standalone to disable sandboxing for the failing actions.
Target //:hello failed to build
INFO: Elapsed time: 3.259s, Critical Path: 0.23s
```

**Comment by ulfjack** [comment]
Philipp made some recent changes to sandboxing, which should fix this for the 0.5.0 release.

**Comment by ittaiz** [comment]
is this resolved?

**Comment by philwo** [comment]
It should be resolved. I'm not sure if we have an integration test for it - if not, I'll add one later this week.
