### ISSUE TITLE
Release - October 2017 - Target RC date: 2017-10-02 - name: 0.7.0

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/bazel#3771]
Release tracking bug for october 2017:
  * Target cut should be 2nd of October (first business day of october)
  * Name: 0.7.0

/cc @dslomov. @aehlig is the only sheriff that hasn't been Release Manager so far so he was scheduled to be the next one.

**Comment by damienmg** [comment]
As talked offline: Klaus is ok to be RM, the tricky thing is that 2nd is business days but the rest of the week are days off for MUC, so if we do not cut on 2nd, the cut date will be 9/10th-ish

**Comment by aehlig** [comment]
I had a look at the last ci-runs, i.e., those for 5cc6246d429f7d9119b97ce263b4fd6893222e92. Unless I missed something (the UI is slightly confusing), it seems that the only failures are those with the error message `clang: error: invalid iOS deployment version '-mios-simulator-version-min=11.0', iOS 10 is the maximum deployment target for 32-bit targets`, i.e., #3841, and that looks more like a mismatch in our test setup or a feature request ("support newer SDK"), not a regression. So I'm considering declaring 5cc6246d429f7d9119b97ce263b4fd6893222e92 as the baseline.

**Comment by aehlig** [comment]
Discussed with @vladmos and it seems fine to take 5cc6246d429f7d9119b97ce263b4fd6893222e92 as baseline. Will try to create a release candidate for that.

**Comment by aehlig** [comment]
rc1 created. https://storage.googleapis.com/bazel/0.7.0/rc1/index.html

Baseline 5cc6246d429f7d9119b97ce263b4fd6893222e92, no cherry picks

**Comment by damienmg** [comment]
@brandjon told me that there is a lot of cherry-picks in current Blaze release inside Google, that might impact 0.7.0 baseline.

**Comment by brandjon** [comment]
Actually since it was cut on Monday, I think there aren't any particular cherry picks to worry about (yet). The ones I was concerned about were actually depot fixes.

**Comment by damienmg** [comment]
https://github.com/bazelbuild/bazel/issues/3863 release blocker

**Comment by aehlig** [comment]
New release candidate (rc2).
https://storage.googleapis.com/bazel/0.7.0/rc2/index.html

Baseline (still) 5cc6246d429f7d9119b97ce263b4fd6893222e92,
Cherry-pick e79a1107d90380501102990d82cbfaa8f51a1778 to fix #3863.

-- 
Klaus Aehlig
Google Germany GmbH, Erika-Mann-Str. 33, 80636 Muenchen
Registergericht und -nummer: Hamburg, HRB 86891
Sitz der Gesellschaft: Hamburg
Geschaeftsfuehrer: Paul Terence Manicle, Halimah DeLaine Prado

**Comment by ola-rozenfeld** [comment]
Hi!

We need https://github.com/bazelbuild/bazel/commit/014408ead21d07bfa41af88b0dba251182e56aff and https://github.com/bazelbuild/bazel/commit/0ebb3e54fc890946ae6b3d059ecbd50e4b5ec840 to be cherrypicked into 0.7.0. Both are fixes to bugs that break our clients. The first one is especially important, since I accidentally broke everyone who passed a non-UUID string as a build request id, which turned out to be a few different teams.

Thank you!

**Comment by aehlig** [comment]
> We need https://github.com/bazelbuild/bazel/commit/014408ead21d07bfa41af88b0dba251182e56aff and https://github.com/bazelbuild/bazel/commit/0ebb3e54fc890946ae6b3d059ecbd50e4b5ec840 to be cherrypicked into 0.7.0.

As confirmed with @damienmg none of those changes fixes a regression
with respect to the last release (0.6.1) and we normally only cherry-pick
those.

Even worse, 014408ead21d07bfa41af88b0dba251182e56aff is not even a bug
fix, but brings an incompatible change to an interface: bazel used to
promise to always report a syntactically correct RFC-style UUIDs; with
that change this is no longer the case. Hence, at least according to
my understanding, it would even be against our release policy to
cherry-pick that change, as it would introduce an incompatible change
in a cherry-pick. (Side note: if the justification is that clients do
not provide an RFC-style UUID where they are supposed to do so, then
the right thing might be to fix the clients anyway.)

-- 
Klaus Aehlig
Google Germany GmbH, Erika-Mann-Str. 33, 80636 Muenchen
Registergericht und -nummer: Hamburg, HRB 86891
Sitz der Gesellschaft: Hamburg
Geschaeftsfuehrer: Paul Terence Manicle, Halimah DeLaine Prado

**Comment by ola-rozenfeld** [comment]
"as it would introduce an incompatible change in a cherry-pick"
It's the other way around -- the cherrypick will *fix* the incompatible change. Bazel never promised to report syntactically correct UUIDs -- in fact, a few teams rely on neither Bazel nor Blaze promising that. The incompatible change was 6f32d5a7d75ff46de6efc557c1ea95777ea813ca, which is merged long ago (and we absolutely need that one in, which is why I fixed it forward instead of rolling back).
Now, I agree that Bazel should use syntactically correct UUIDs, and I also thought that we should fix the clients instead, but that's a separate ongoing discussion with the teams that rely on the incorrect ids (they don't want to fix it unless we provide another way for them to pass in easily identifiable prefixes).

Re: 0ebb3e54fc890946ae6b3d059ecbd50e4b5ec840 -- yes, it is just a bug, not a regression, but a very annoying one -- can we have it as a patch, then, in 0.7.1? We're trying to support the latest Bazel release, and because of this bug we simply cannot -- it systematically breaks our integration tests. This is why we rely on our custom build instead.

**Comment by damienmg** [comment]
for 014408e it is indeed true that 6f32d5a forced to have a syntactically correct UUID and was a breaking change and 014408e is reverting that. The justification for cherry-pick is largely missing from the commit description and I still don't know users of Bazel that are broken by that change. IIUC this was a fix for our internal release at Google to interact with internal service. If I misunderstood it, there might be a reason for cherry-picking it, but for now I consider this as a non-regression. Feel free to mail me directly to discuss further.

To simplify the discussion that would be great for those kind of fix to have:
  1. A clear bug that state the impact. Please have one open on github, if there is confidential information you can always have an internal bug number on the github issue.
  2. An explanation of the regression it fixes on the CL description.
  3. Best-practice: a link to the release bug it needs to be in (e.g.: To cherry-pick for #3771)

For 0ebb3e5, I can see it being annoying but I think we should just cherry-pick it if we do anymore cherry-pick (i.e. would go into 0.7.0 if we have more cherry-pick for it, can be a justification for a 0.7.1). Pulling another lead to have a second opinion on this one: @dslomov

**Comment by dslomov** [comment]
My general recommendation: do not rely on stuff being cherry-picked into releases. Instead, if what you work on relies on continuous changes in Bazel, work off nightlies to detect problems early and make sure that by release time (known well in advance now) all your ducks are in a neat row :)

I do not mind cherry-picking 0ebb3e5 because it is an annoying bug and the fix is safe.

**Comment by damienmg** [comment]
Ok so for 0ebb3e5 I propose the following: we will cherry-pick it if we do a patch release or another cherry-pick. @aehlig @dslomov: do that sgty?

**Comment by dslomov** [comment]
Ok with me (falls under ~critical bug provision)

**Comment by ola-rozenfeld** [comment]
Thank you, SGTM!

Re: "make sure that by release time (known well in advance now) all your
ducks are in a neat row" -- actually, qq about the procedure on that --
after making the change internally, I was obsessively reloading the Bazel
commits page for days to see when my change appears externally, so that I
can ask for the cherrypick. It had a delay of a few days between internal
submission and external patch, and I asked as soon as I had the external
patch id. Should I have contacted you guys about the cherrypick as soon as
the change was submitted internally? Asking for the next time :-)

And yes, I just learned that you have nightly releases, and indeed we are
switching to work off of that instead.

**Comment by damienmg** [comment]
No need to ask before it hit the repo. And hopefully this won't be long before we switch to CaaS anyway.

**Comment by aehlig** [comment]
On Thu, Oct 12, 2017 at 11:57:01AM +0000, Damien Martin-Guillerez wrote:
> Ok so for 0ebb3e5 I propose the following: we will cherry-pick it if we do a patch release or another cherry-pick. @aehlig @dslomov: do that sgty?

Sounds good.

-- 
Klaus Aehlig
Google Germany GmbH, Erika-Mann-Str. 33, 80636 Muenchen
Registergericht und -nummer: Hamburg, HRB 86891
Sitz der Gesellschaft: Hamburg
Geschaeftsfuehrer: Paul Terence Manicle, Halimah DeLaine Prado

**Comment by ittaiz** [comment]
Hi,
Any idea when this will be released?

**Comment by damienmg** [comment]
There is a new issue touching remote execution, see https://bazel-review.googlesource.com/c/bazel/+/19111

**Comment by aehlig** [comment]
@ittaiz 

> Any idea when this will be released?

My plan was to release today, unless the new issue mentioned my @damienmg turns out to be a regression with respect to 0.6.1. However, from what I was told, I got the impression that that change fixes an issue that was only introduced after the baseline 5cc6246d429f7d9119b97ce263b4fd6893222e92. But I'll have to verify this.

**Comment by aehlig** [comment]
My understanding is that https://bazel-review.googlesource.com/c/bazel/+/19111 addresses an issue introduced by f6b8d5e269cf64bda483af464ad98af7277728a6 which is well after our baseline. 

@damienmg, you mentioned this issue in the context of this release; can you explain how it affects it?

**Comment by damienmg** [comment]
As I said on the mail thread I missed the fact that the issue happened
after the candidate was cut so imo 0.7 is good to go :)

**Comment by aehlig** [comment]
Will promote rc2 to release.

**Comment by aehlig** [comment]
Released (code as `rc2`, i.e., baseline 5cc6246d429f7d9119b97ce263b4fd6893222e92 with cherry pick e79a1107d90380501102990d82cbfaa8f51a1778).

https://github.com/bazelbuild/bazel/releases/tag/0.7.0
https://storage.googleapis.com/bazel/0.7.0/release/index.html

**Comment by petemounce** [comment]
Pushed https://chocolatey.org/packages/bazel/0.7.0 - only just noticed this issue, wasn't pinged.

**Comment by damienmg** [comment]
Sorry for that @petemounce, all the release are now labelled "release": https://github.com/bazelbuild/bazel/labels/release, should be easier to follow.

**Comment by petemounce** [comment]
np, thanks for the label!
