### ISSUE TITLE
CI, bazel-nightly: TF, TF serving, and bazel-tests are failing

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#4233]
https://ci.bazel.io/job/Global/job/TensorFlow/311/console
https://ci.bazel.io/job/Global/job/TensorFlow_Serving/301/consoleFull
https://ci.bazel.io/job/Global/job/bazel-tests/383/consoleFull

Likely culprit: 7cf1c694a3f949717be06b3b6c8e6a20e22cb83f

The test ran with a Bazel binary built at https://github.com/bazelbuild/bazel/commit/ddd5ac16aeffa6c4693c348f73e7365240b1abc5.

EDIT(2017-12-06): this should not block https://github.com/bazelbuild/bazel/issues/3773 because it's not a bug in Bazel, it requires updating some BUILD files.
~Blocking: https://github.com/bazelbuild/bazel/issues/3773~

Example log:
```
[variation=,node=linux-x86_64] ERROR: /home/ci/.cache/bazel/_bazel_ci/c84992ee451c4a2c1cb221074029893a/external/local_config_sycl/sycl/BUILD:4:1: First argument of 'load' must be a label and start with either '//', ':', or '@'. Use --incompatible_load_argument_is_label=false to temporarily disable this check.
[variation=,node=linux-x86_64] ERROR: /home/ci/.cache/bazel/_bazel_ci/c84992ee451c4a2c1cb221074029893a/external/local_config_sycl/sycl/BUILD:6:1: First argument of 'load' must be a label and start with either '//', ':', or '@'. Use --incompatible_load_argument_is_label=false to temporarily disable this check.
[variation=,node=linux-x86_64] ERROR: /home/ci/.cache/bazel/_bazel_ci/c84992ee451c4a2c1cb221074029893a/external/local_config_sycl/sycl/BUILD:41:9: Traceback (most recent call last):
[variation=,node=linux-x86_64] 	File "/home/ci/.cache/bazel/_bazel_ci/c84992ee451c4a2c1cb221074029893a/external/local_config_sycl/sycl/BUILD", line 38
[variation=,node=linux-x86_64] 		cc_library(name = "syclrt", srcs = [sycl_libr...")], <3 more arguments>)
[variation=,node=linux-x86_64] 	File "/home/ci/.cache/bazel/_bazel_ci/c84992ee451c4a2c1cb221074029893a/external/local_config_sycl/sycl/BUILD", line 41, in cc_library
[variation=,node=linux-x86_64] 		sycl_library_path
[variation=,node=linux-x86_64] name 'sycl_library_path' is not defined
[variation=,node=linux-x86_64] Analyzing: target //tensorflow/tools/pip_package:build_pip_package (86 packages loaded)
[variation=,node=linux-x86_64] ERROR: /home/ci/.cache/bazel/_bazel_ci/c84992ee451c4a2c1cb221074029893a/external/local_config_sycl/sycl/BUILD:50:1: Target '@local_config_sycl//sycl:using_sycl_ccpp' contains an error and its package is in error and referenced by '@local_config_sycl//sycl:sycl'
[variation=,node=linux-x86_64] ERROR: /home/ci/.cache/bazel/_bazel_ci/c84992ee451c4a2c1cb221074029893a/external/local_config_sycl/sycl/BUILD:50:1: Target '@local_config_sycl//sycl:using_sycl_trisycl' contains an error and its package is in error and referenced by '@local_config_sycl//sycl:sycl'
[variation=,node=linux-x86_64] ERROR: /home/ci/workspace/Global/TensorFlow-variation=,node=linux-x86_64/third_party/eigen3/BUILD:20:1: Target '@local_config_sycl//sycl:sycl' contains an error and its package is in error and referenced by '//third_party/eigen3:eigen3'
[variation=,node=linux-x86_64] ERROR: Analysis of target '//tensorflow/tools/pip_package:build_pip_package' failed; build aborted: Loading failed
[variation=,node=linux-x86_64] INFO: Elapsed time: 6.003s
[variation=,node=linux-x86_64] FAILED: Build did NOT complete successfully (86 packages loaded)
[variation=,node=linux-x86_64] FAILED: Build did NOT complete successfully (86 packages loaded)
```

https://ci.bazel.io/job/Global/job/bazel-tests/383/consoleFull example log:
```
[node=windows-x86_64,toolchain=msvc] [bazel-tests-node=windows-x86_64,toolchain=msvc] Running batch script
[node=windows-x86_64,toolchain=msvc] 
[node=windows-x86_64,toolchain=msvc] c:\jenkins\workspace\Global\bazel-tests-node=windows-x86_64,toolchain=msvc>c:\bazel_ci\installs\custom\bazel_nightly\144\variation_\bazel.exe --bazelrc=c:\jenkins\workspace\Global\bazel-tests-node=windows-x86_64,toolchain=msvc/bazel.bazelrc test //src:all_windows_tests  
[node=windows-x86_64,toolchain=msvc] Loading: 
[node=windows-x86_64,toolchain=msvc] Loading: 0 packages loaded
[node=windows-x86_64,toolchain=msvc] DEBUG: C:/windows/temp/_bazel_system/yuv-tl0g/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:37:3: 
[node=windows-x86_64,toolchain=msvc] Auto-Configuration Warning: 'BAZEL_VC' is not set, start looking for the latest Visual C++ installed.
[node=windows-x86_64,toolchain=msvc] DEBUG: C:/windows/temp/_bazel_system/yuv-tl0g/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:37:3: 
[node=windows-x86_64,toolchain=msvc] Auto-Configuration Warning: Looking for VS%VERSION%COMNTOOLS environment variables,eg. VS140COMNTOOLS
[node=windows-x86_64,toolchain=msvc] DEBUG: C:/windows/temp/_bazel_system/yuv-tl0g/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:37:3: 
[node=windows-x86_64,toolchain=msvc] Auto-Configuration Warning: Visual C++ build tools found at C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\
[node=windows-x86_64,toolchain=msvc] ERROR: C:/windows/temp/_bazel_system/yuv-tl0g/external/com_googlesource_code_re2/BUILD:97:1: First argument of 'load' must be a label and start with either '//', ':', or '@'. Use --incompatible_load_argument_is_label=false to temporarily disable this check.
[node=windows-x86_64,toolchain=msvc] ERROR: C:/windows/temp/_bazel_system/yuv-tl0g/external/com_googlesource_code_re2/BUILD:99:1: name 're2_test' is not defined (did you mean 'ios_test'?)
(...)
[node=windows-x86_64,toolchain=msvc] ERROR: C:/windows/temp/_bazel_system/yuv-tl0g/external/com_googlesource_code_re2/BUILD:152:1: name 're2_test' is not defined (did you mean 'ios_test'?)
[node=windows-x86_64,toolchain=msvc] Analyzing: 114 targets (51 packages loaded)
[node=windows-x86_64,toolchain=msvc] ERROR: C:/windows/temp/_bazel_system/yuv-tl0g/external/com_googlesource_code_re2/BUILD:11:1: Target '@com_googlesource_code_re2//:re2/bitmap256.h' contains an error and its package is in error and referenced by '@com_googlesource_code_re2//:re2'
```

**Comment by laszlocsomor** [comment]
@iirina FYI

**Comment by laurentlb** [comment]
The first failure in Tensorflow is https://github.com/tensorflow/tensorflow/issues/15137

**Comment by laurentlb** [comment]
The other error in "re2/BUILD:97" was fixed here: https://github.com/google/re2/commit/884287d109ec987e8029ae0a9cebe66223283998

**Comment by laszlocsomor** [comment]
Marking this as non-blocker for #3773 because it's not a bug in Bazel, it requires updating some BUILD files.

**Comment by laszlocsomor** [comment]
I tested https://github.com/bazelbuild/bazel/commit/2cf560f83922e6df9626ba3ee063c1caf6797548 locally. It fixes the `load()`-related errors on Windows in https://ci.bazel.io/job/Global/job/bazel-tests/383/consoleFull, but `//src/test/py/bazel:bazel_windows_cpp_test` and `//src/test/py/bazel:bazel_windows_test` are still failing. I'll file a separate issue.
