### ISSUE TITLE
Unable to load rules from external repository BUILD file

### ISSUE THREAD

**Issue by davidzchen** [bazelbuild/bazel#429]
It seems that extension files cannot be found when they are loaded in a BUILD file used as the `build_file` for a `new_*` workspace rule.

Repro scenario: https://github.com/davidzchen/examples/tree/rust/rust

When running `bazel build @traitobject//:traitobject`:

```
❯❯❯ bazel build @traitobject//:traitobject
ERROR: /usr/local/google/home/dzc/.cache/bazel/_bazel_dzc/ceb134e58b01943542e861bd8d894539/external/traitobject/BUILD:1: Extension file not found: 'tools/build_rules/rust/rust.bzl'.
ERROR: error loading package '@traitobject//': Extension file not found: 'tools/build_rules/rust/rust.bzl'.
INFO: Elapsed time: 0.083s
```

**Comment by kchodorow** [comment]
At the moment, load() takes a path so as of ~1 week ago we made it a "local" path (external repositories can only find .bzl files within their repository).  @jhfield  is working on making load() take a label, so you'll be able to specify more flexibly where a .bzl file is.

**Comment by davidzchen** [comment]
Understood. Thanks! I'll look forward to it.

**Comment by abergmeier** [comment]
Just hit this problem with trying to integrate `boost`. That said, I saw https://github.com/bazelbuild/bazel/commit/925dc5ce1c6916b43a94fa12017aa4a6390de891 and am wondering what a rough ETA for having this available in Skylark is @jhfield .

**Comment by benley** [comment]
I'm stuck on this now too, trying to write bazel rules for some open-source Go libraries.  Any suggestions for temporary workarounds?

**Comment by davidzchen** [comment]
Here is a temporary workaround from the mailing list: https://groups.google.com/forum/#!searchin/bazel-discuss/external/bazel-discuss/mlocXdN-3Wk/J9ivt3q-DgAJ

From what I understand, 925dc5c was later rolled back in 2a7c802823a0bc59d2cb010962e250ee145c620c because it broke some tests.

@jhfield - Is there an ETA on the fix for this?

**Comment by kchodorow** [comment]
This should be fixed as of 1ea7fc370f0605be2185868f9371f6e04c26a502.

**Comment by dmansfield** [comment]
Is this syntax supposed to work in a WORKSPACE file or only in BUILD files? (I'm having difficulty with it working in a WORKSPACE file with 0.3.0)

**Comment by dmansfield** [comment]
Nevermind. I was missing something obvious. Works fine.

**Comment by lingz** [comment]
@dmansfield what was the obvious thing you were missing? I can get it on WORKSPACE but not BUILD.

**Comment by kgreenek** [comment]
I am still getting this problem actually. I have a *.bzl file located at //bzl/glob_cc_proto_hdr.bzl. I'm trying to load it from a BUILD file that is being passed to an external workspace created by new_git_repository. Here's the error I am getting:

ERROR: /home/kevin/Projects/first_commit/WORKSPACE:55:1: error loading package '@ign_msgs_archive//': Extension file not found. Unable to load package for '@ign_msgs_archive//bzl:glob_cc_proto_hdr.bzl': BUILD file not found on package path and referenced by '//external:ign_msgs_factory'.

The load statement (in ign_msgs.BUILD) looks like this:
load("//bzl:glob_cc_proto_hdr.bzl", "glob_cc_proto_hdr")

Notice that the path is relative to @ign_msgs_archive (the external project), not my project workspace. So I'm unable to use that bazel rule in the ign_msgs.BUILD file.

**Comment by AustinSchuh** [comment]
Try @//bzl:glob_cc_proto_hdr.bzl .  That will load it from the main
workspace.

Austin

**Comment by kgreenek** [comment]
Ah, Thanks @AustinSchuh! Exactly what I needed.
