### ISSUE TITLE
--action_env results in confusing and inconsistent behavior

### ISSUE THREAD

**Issue by crorvick** [bazelbuild/bazel#4643]
### Description of the problem / feature request:

Bazel has two forms for passing environment variables into the build via the `--action_env` command-line parameter:

- **NAME only:** the variable is passed into Bazel, getting the value from the user's environment.
- **NAME=value:** the variable is passed into Bazel with the explicitly provided value

I have stumbled into some surprising observations:

- Variables passed via `--action_env` are not set in all task environments (e.g., compiling for host.)
- Which tasks have the variable in their environment is dependent on which form is used.

Both of these appear to be bugs based on my understanding of how `--action_env` should work from the documentation.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.
Example 1:
```
$ git clone https://github.com/crorvick/bazel-hello.git
$ cd bazel-hello
$ bazel build --action_env=MY_VARIABLE=nothing_special -s //src/hello
```
Example 2:
```
$ bazel clean
$ bazel shutdown
$ MY_VARIABLE=nothing_special bazel build --action_env=MY_VARIABLE -s //src/hello
```
In both examples tasks are run without `MY_VARIABLE` set in their environments.  The tasks that do see `MY_VARIABLE` are not consistent between the examples (i.e., example 2 sees fewer)

### What operating system are you running Bazel on?

1. CentOS 7.4
2. Gentoo

(reproducible on both)

### What's the output of `bazel info release`?

1. CentOS 7.4: `release 0.10.0- (@non-git)`
2. Gentoo: `release 0.7.0- (@non-git)`

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

1. CentOS 7.4:
   1. download tarball from GitHub (`bazel-0.10.0-dist.zip`)
   2. run `compile.sh` from exploded tarball

2. Gentoo
   1. run `emerge` with `~amd64` enabled for `dev-util/bazel`

### Output from example runs

Example 1:
```
$ bazel build --action_env=MY_VARIABLE=nothing_special -s //src/hello
INFO: Found 1 target...
>>>>> # //src/hello:hello [action 'Creating runfiles tree bazel-out/local-fastbuild/bin/src/hello/hello.runfiles']
(cd /home/chris/.cache/bazel/_bazel_chris/009fe0b206b9fa4bf70b52aad8fd454d/execroot/__main__ && \
  exec env - \
    MY_VARIABLE=nothing_special \
    PATH=/usr/local/bin:/usr/bin:/bin:/usr/x86_64-pc-linux-gnu/gcc-bin/7.3.0:/usr/lib/llvm/5/bin:/usr/lib/llvm/4/bin:/usr/local/bin:/usr/bin:/bin:/opt/bin:/usr/games/bin \
  _bin/build-runfiles bazel-out/local-fastbuild/bin/src/hello/hello.runfiles_manifest bazel-out/local-fastbuild/bin/src/hello/hello.runfiles)
>>>>> # //src/optimize:optimize [action 'Creating runfiles tree bazel-out/host/bin/src/optimize/optimize.runfiles [for host]']
(cd /home/chris/.cache/bazel/_bazel_chris/009fe0b206b9fa4bf70b52aad8fd454d/execroot/__main__ && \
  exec env - \
    PATH=/usr/local/bin:/usr/bin:/bin:/usr/x86_64-pc-linux-gnu/gcc-bin/7.3.0:/usr/lib/llvm/5/bin:/usr/lib/llvm/4/bin:/usr/local/bin:/usr/bin:/bin:/opt/bin:/usr/games/bin \
  _bin/build-runfiles bazel-out/host/bin/src/optimize/optimize.runfiles_manifest bazel-out/host/bin/src/optimize/optimize.runfiles)
>>>>> # //src/optimize:optimize [action 'Compiling src/optimize/main.cc [for host]']
(cd /home/chris/.cache/bazel/_bazel_chris/009fe0b206b9fa4bf70b52aad8fd454d/execroot/__main__ && \
  exec env - \
    PATH=/usr/local/bin:/usr/bin:/bin:/usr/x86_64-pc-linux-gnu/gcc-bin/7.3.0:/usr/lib/llvm/5/bin:/usr/lib/llvm/4/bin:/usr/local/bin:/usr/bin:/bin:/opt/bin:/usr/games/bin \
    PWD=/proc/self/cwd \
  /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -B/usr/bin -B/usr/bin -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections -fdata-sections -g0 '-std=c++0x' -g0 -MD -MF bazel-out/host/bin/src/optimize/_objs/optimize/src/optimize/main.d '-frandom-seed=bazel-out/host/bin/src/optimize/_objs/optimize/src/optimize/main.o' -iquote . -iquote bazel-out/host/genfiles -iquote external/bazel_tools -iquote bazel-out/host/genfiles/external/bazel_tools -isystem external/bazel_tools/tools/cpp/gcc3 -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c src/optimize/main.cc -o bazel-out/host/bin/src/optimize/_objs/optimize/src/optimize/main.o)
>>>>> # //src/optimize:optimize [action 'Linking src/optimize/optimize [for host]']
(cd /home/chris/.cache/bazel/_bazel_chris/009fe0b206b9fa4bf70b52aad8fd454d/execroot/__main__ && \
  exec env - \
    PATH=/usr/local/bin:/usr/bin:/bin:/usr/x86_64-pc-linux-gnu/gcc-bin/7.3.0:/usr/lib/llvm/5/bin:/usr/lib/llvm/4/bin:/usr/local/bin:/usr/bin:/bin:/opt/bin:/usr/games/bin \
    PWD=/proc/self/cwd \
  /usr/bin/gcc -o bazel-out/host/bin/src/optimize/optimize '-fuse-ld=gold' -Wl,-no-as-needed -Wl,-z,relro,-z,now -B/usr/bin -B/usr/bin -pass-exit-codes -Wl,--gc-sections -Wl,-S -Wl,@bazel-out/host/bin/src/optimize/optimize-2.params)
>>>>> # //src/hello:hello_optimize [action 'Executing genrule //src/hello:hello_optimize']
(cd /home/chris/.cache/bazel/_bazel_chris/009fe0b206b9fa4bf70b52aad8fd454d/execroot/__main__ && \
  exec env - \
    MY_VARIABLE=nothing_special \
    PATH=/usr/local/bin:/usr/bin:/bin:/usr/x86_64-pc-linux-gnu/gcc-bin/7.3.0:/usr/lib/llvm/5/bin:/usr/lib/llvm/4/bin:/usr/local/bin:/usr/bin:/bin:/opt/bin:/usr/games/bin \
  /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; bazel-out/host/bin/src/optimize/optimize <src/hello/hello.in >bazel-out/local-fastbuild/genfiles/src/hello/hello.cc')
>>>>> # //src/hello:hello [action 'Compiling src/hello/hello.cc']
(cd /home/chris/.cache/bazel/_bazel_chris/009fe0b206b9fa4bf70b52aad8fd454d/execroot/__main__ && \
  exec env - \
    MY_VARIABLE=nothing_special \
    PATH=/usr/local/bin:/usr/bin:/bin:/usr/x86_64-pc-linux-gnu/gcc-bin/7.3.0:/usr/lib/llvm/5/bin:/usr/lib/llvm/4/bin:/usr/local/bin:/usr/bin:/bin:/opt/bin:/usr/games/bin \
    PWD=/proc/self/cwd \
  /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -B/usr/bin -B/usr/bin -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer '-std=c++0x' -MD -MF bazel-out/local-fastbuild/bin/src/hello/_objs/hello/src/hello/hello.pic.d '-frandom-seed=bazel-out/local-fastbuild/bin/src/hello/_objs/hello/src/hello/hello.pic.o' -fPIC -iquote . -iquote bazel-out/local-fastbuild/genfiles -iquote external/bazel_tools -iquote bazel-out/local-fastbuild/genfiles/external/bazel_tools -isystem external/bazel_tools/tools/cpp/gcc3 -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c bazel-out/local-fastbuild/genfiles/src/hello/hello.cc -o bazel-out/local-fastbuild/bin/src/hello/_objs/hello/src/hello/hello.pic.o)
>>>>> # //src/hello:hello [action 'Linking src/hello/hello']
(cd /home/chris/.cache/bazel/_bazel_chris/009fe0b206b9fa4bf70b52aad8fd454d/execroot/__main__ && \
  exec env - \
    MY_VARIABLE=nothing_special \
    PATH=/usr/local/bin:/usr/bin:/bin:/usr/x86_64-pc-linux-gnu/gcc-bin/7.3.0:/usr/lib/llvm/5/bin:/usr/lib/llvm/4/bin:/usr/local/bin:/usr/bin:/bin:/opt/bin:/usr/games/bin \
    PWD=/proc/self/cwd \
  /usr/bin/gcc -o bazel-out/local-fastbuild/bin/src/hello/hello '-fuse-ld=gold' -Wl,-no-as-needed -Wl,-z,relro,-z,now -B/usr/bin -B/usr/bin -pass-exit-codes -Wl,-S -Wl,@bazel-out/local-fastbuild/bin/src/hello/hello-2.params)
Target //src/hello:hello up-to-date:
  bazel-bin/src/hello/hello
INFO: Elapsed time: 1.395s, Critical Path: 0.60s
```
Example 2:
```
$ MY_VARIABLE=nothing_special bazel build --action_env=MY_VARIABLE -s //src/hello
INFO: Found 1 target...
>>>>> # //src/hello:hello [action 'Creating runfiles tree bazel-out/local-fastbuild/bin/src/hello/hello.runfiles']
(cd /home/chris/.cache/bazel/_bazel_chris/009fe0b206b9fa4bf70b52aad8fd454d/execroot/__main__ && \
  exec env - \
    PATH=/usr/local/bin:/usr/bin:/bin:/usr/x86_64-pc-linux-gnu/gcc-bin/7.3.0:/usr/lib/llvm/5/bin:/usr/lib/llvm/4/bin:/usr/local/bin:/usr/bin:/bin:/opt/bin:/usr/games/bin \
  _bin/build-runfiles bazel-out/local-fastbuild/bin/src/hello/hello.runfiles_manifest bazel-out/local-fastbuild/bin/src/hello/hello.runfiles)
>>>>> # //src/optimize:optimize [action 'Compiling src/optimize/main.cc [for host]']
(cd /home/chris/.cache/bazel/_bazel_chris/009fe0b206b9fa4bf70b52aad8fd454d/execroot/__main__ && \
  exec env - \
    PATH=/usr/local/bin:/usr/bin:/bin:/usr/x86_64-pc-linux-gnu/gcc-bin/7.3.0:/usr/lib/llvm/5/bin:/usr/lib/llvm/4/bin:/usr/local/bin:/usr/bin:/bin:/opt/bin:/usr/games/bin \
    PWD=/proc/self/cwd \
  /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -B/usr/bin -B/usr/bin -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections -fdata-sections -g0 '-std=c++0x' -g0 -MD -MF bazel-out/host/bin/src/optimize/_objs/optimize/src/optimize/main.d '-frandom-seed=bazel-out/host/bin/src/optimize/_objs/optimize/src/optimize/main.o' -iquote . -iquote bazel-out/host/genfiles -iquote external/bazel_tools -iquote bazel-out/host/genfiles/external/bazel_tools -isystem external/bazel_tools/tools/cpp/gcc3 -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c src/optimize/main.cc -o bazel-out/host/bin/src/optimize/_objs/optimize/src/optimize/main.o)
>>>>> # //src/optimize:optimize [action 'Creating runfiles tree bazel-out/host/bin/src/optimize/optimize.runfiles [for host]']
(cd /home/chris/.cache/bazel/_bazel_chris/009fe0b206b9fa4bf70b52aad8fd454d/execroot/__main__ && \
  exec env - \
    PATH=/usr/local/bin:/usr/bin:/bin:/usr/x86_64-pc-linux-gnu/gcc-bin/7.3.0:/usr/lib/llvm/5/bin:/usr/lib/llvm/4/bin:/usr/local/bin:/usr/bin:/bin:/opt/bin:/usr/games/bin \
  _bin/build-runfiles bazel-out/host/bin/src/optimize/optimize.runfiles_manifest bazel-out/host/bin/src/optimize/optimize.runfiles)
>>>>> # //src/optimize:optimize [action 'Linking src/optimize/optimize [for host]']
(cd /home/chris/.cache/bazel/_bazel_chris/009fe0b206b9fa4bf70b52aad8fd454d/execroot/__main__ && \
  exec env - \
    PATH=/usr/local/bin:/usr/bin:/bin:/usr/x86_64-pc-linux-gnu/gcc-bin/7.3.0:/usr/lib/llvm/5/bin:/usr/lib/llvm/4/bin:/usr/local/bin:/usr/bin:/bin:/opt/bin:/usr/games/bin \
    PWD=/proc/self/cwd \
  /usr/bin/gcc -o bazel-out/host/bin/src/optimize/optimize '-fuse-ld=gold' -Wl,-no-as-needed -Wl,-z,relro,-z,now -B/usr/bin -B/usr/bin -pass-exit-codes -Wl,--gc-sections -Wl,-S -Wl,@bazel-out/host/bin/src/optimize/optimize-2.params)
>>>>> # //src/hello:hello_optimize [action 'Executing genrule //src/hello:hello_optimize']
(cd /home/chris/.cache/bazel/_bazel_chris/009fe0b206b9fa4bf70b52aad8fd454d/execroot/__main__ && \
  exec env - \
    MY_VARIABLE=nothing_special \
    PATH=/usr/local/bin:/usr/bin:/bin:/usr/x86_64-pc-linux-gnu/gcc-bin/7.3.0:/usr/lib/llvm/5/bin:/usr/lib/llvm/4/bin:/usr/local/bin:/usr/bin:/bin:/opt/bin:/usr/games/bin \
  /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; bazel-out/host/bin/src/optimize/optimize <src/hello/hello.in >bazel-out/local-fastbuild/genfiles/src/hello/hello.cc')
>>>>> # //src/hello:hello [action 'Compiling src/hello/hello.cc']
(cd /home/chris/.cache/bazel/_bazel_chris/009fe0b206b9fa4bf70b52aad8fd454d/execroot/__main__ && \
  exec env - \
    PATH=/usr/local/bin:/usr/bin:/bin:/usr/x86_64-pc-linux-gnu/gcc-bin/7.3.0:/usr/lib/llvm/5/bin:/usr/lib/llvm/4/bin:/usr/local/bin:/usr/bin:/bin:/opt/bin:/usr/games/bin \
    PWD=/proc/self/cwd \
  /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -B/usr/bin -B/usr/bin -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer '-std=c++0x' -MD -MF bazel-out/local-fastbuild/bin/src/hello/_objs/hello/src/hello/hello.pic.d '-frandom-seed=bazel-out/local-fastbuild/bin/src/hello/_objs/hello/src/hello/hello.pic.o' -fPIC -iquote . -iquote bazel-out/local-fastbuild/genfiles -iquote external/bazel_tools -iquote bazel-out/local-fastbuild/genfiles/external/bazel_tools -isystem external/bazel_tools/tools/cpp/gcc3 -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c bazel-out/local-fastbuild/genfiles/src/hello/hello.cc -o bazel-out/local-fastbuild/bin/src/hello/_objs/hello/src/hello/hello.pic.o)
>>>>> # //src/hello:hello [action 'Linking src/hello/hello']
(cd /home/chris/.cache/bazel/_bazel_chris/009fe0b206b9fa4bf70b52aad8fd454d/execroot/__main__ && \
  exec env - \
    PATH=/usr/local/bin:/usr/bin:/bin:/usr/x86_64-pc-linux-gnu/gcc-bin/7.3.0:/usr/lib/llvm/5/bin:/usr/lib/llvm/4/bin:/usr/local/bin:/usr/bin:/bin:/opt/bin:/usr/games/bin \
    PWD=/proc/self/cwd \
  /usr/bin/gcc -o bazel-out/local-fastbuild/bin/src/hello/hello '-fuse-ld=gold' -Wl,-no-as-needed -Wl,-z,relro,-z,now -B/usr/bin -B/usr/bin -pass-exit-codes -Wl,-S -Wl,@bazel-out/local-fastbuild/bin/src/hello/hello-2.params)
Target //src/hello:hello up-to-date:
  bazel-bin/src/hello/hello
INFO: Elapsed time: 1.436s, Critical Path: 0.63s
```

**Comment by aehlig** [comment]
Over to @mhlopko, as the inconsistencies are in the C native rules.

-- 
Klaus Aehlig
Google Germany GmbH, Erika-Mann-Str. 33, 80636 Muenchen
Registergericht und -nummer: Hamburg, HRB 86891
Sitz der Gesellschaft: Hamburg
Geschaeftsfuehrer: Paul Terence Manicle, Halimah DeLaine Prado

**Comment by crorvick** [comment]
Hello @mhlopko, can you elaborate on the reason for priority change?

**Comment by mhlopko** [comment]
cc @ulfjack

**Comment by mhlopko** [comment]
cc @philwo is https://github.com/bazelbuild/bazel/pull/4304 related?

**Comment by crorvick** [comment]
Could someone summarize the current status of this bug report?

**Comment by ulfjack** [comment]
I fixed C++ compilation and linking, as well as build-runfiles invocations. They should all have the right env variables now. See #4750, #5142, and #3642. I'm requesting that they are cherrypicked into the 0.14.0 release.

I have also locked down the code to reduce the likelihood that new violations are introduced in the future. That said, I am fairly sure that there are still bugs in the code. When I first introduced the ActionEnvironment class, I didn't want to also change the semantics of the existing actions, so there may still be places which 'intentionally' do it incorrectly.

**Comment by ulfjack** [comment]
Given that this was reported in the C++ component, I'll close this as fixed. Please let me know if you still see any cases where env variables are not set properly in 0.14.0.

**Comment by crorvick** [comment]
@ulfjack, thanks!

**Comment by crorvick** [comment]
@ulfjack, a quick test of latest in Git looks better, but I still see that the environment variable is not passed through to host targets (e.g., the `//src/optimize:optimize` target in the example.)  Should there be a separate `--host_env` option for this?

**Comment by ulfjack** [comment]
Host action_env is tracked in #6473.
