### ISSUE TITLE
 Permission denied when installed to /usr/local with local .bazelrc

### ISSUE THREAD

**Issue by scytulip** [bazelbuild/bazel#739]
Install Bazel by using

```
$./bazel-0.1.2-installer-linux-x86_64.sh --bazelrc=$HOME/.bazelrc
```

After the installation, if I tried running
$bazel
I'll get an error message

```
Error: mkdir('/home/$USER/.cache/bazel/_bazel_$USER'): Permission denied
```

My solution:

```
$sudo chown $USER:$USER ~/.cache/bazel/
```

**Comment by kchodorow** [comment]
Do you know what the permissions on ~/.cache/bazel/... were before you ran chown?

**Comment by scytulip** [comment]
It belongs to root:root.

BTW, I installed using "$sudo ./bazel-0.1.2-installer-linux-x86_64.sh --bazelrc=$HOME/.bazelrc" because it copied file to /usr/local.......

So, it might be better to initialize the cache when first run bazel but not during the installation.

**Comment by kchodorow** [comment]
Thanks!  We should either build in another directory or use `$SUDO_USER` to get the underlying user.

**Comment by damienmg** [comment]
how is the cache directory computed? The initialization should be ran as root and thus be in `~root/.cache/bazel`. I am pretty sure the problem comes from the launcher.

As a side note: you should do `./installer.sh --user` to install in user location.

**Comment by nkurz** [comment]
Came to report the same problem.   I was trying to install Bazel to compile https://github.com/google/highwayhash.

$ wget https://github.com/bazelbuild/bazel/releases/download/0.2.0/bazel-0.2.0-installer-linux-x86_64.sh
$ sudo bash bazel-0.2.0-installer-linux-x86_64.sh
$ bazel build :all -c opt --copt=-mavx2
Error: mkdir('/home/nate/.cache/bazel/_bazel_nate'): Permission denied
$ ls -ald ~/.cache/bazel/
drwxr-xr-x 3 root root 4096 Mar  2 18:02 /home/nate/.cache/bazel/

Solved with "sudo chown -R $USER:$USER ~/.cache/bazel/".

I don't understand Bazel, but I don't think the problem is just the permissions.   I'd think the cache directory should be per user, rather than being a single directory which all users share.  How are the permissions going to work when a third-party user on the system tries to use Bazel?    Will it try to create a subdirectory within my home directory? 

$ ls -al ~/.cache/bazel/
total 16
drwxr-xr-x 4 nate nate 4096 Mar  2 18:15 .
drwx------ 5 nate nate 4096 Mar  2 18:02 ..
drwxr-xr-x 4 nate nate 4096 Mar  2 18:15 _bazel_nate
drwxr-xr-x 4 nate nate 4096 Mar  2 18:02 _bazel_root

At the least, this seems odd.

**Comment by damienmg** [comment]
The isssue is that the install from the installer see the user home as the
host home (not root).  We should probably just not run bazel if the
installer is run as root.

**Comment by ncullen93** [comment]
I am getting this error.. Is there any way to get around this without root privledges?

**Comment by kchodorow** [comment]
1) Get the bazel installer for 0.4.4 (download here: https://github.com/bazelbuild/bazel/releases/tag/0.4.4). Don't use JDK 7.
2) If "bazel" is the only thing in ~/.cache, run `sudo rm -rf ~/.cache/bazel` (you probably need to run this as sudo because I'm guessing ~/.cache and/or ~/.cache/bazel are owned by root).  Double check this command before running, since it's sudo rm!  (If bazel isn't the only subdirectory, just remove the bazel subdirectory and chown ~/.cache to your user/group.)
3) Run `chmod +x <name of the installer you downloaded>.sh`
4) Run `./<name of the installer you downloaded>.sh --user`

**Comment by ncullen93** [comment]
thanks for the response! yeah I did that and I still get a permission denied error. I don't have root access, I think that's the point I'm trying to make :) Oh well.

**Comment by kchodorow** [comment]
Oh... then how did you get ~/.cache/bazel not owned by you?

Regardless, this error message doesn't really matter. Bazel should already be installed in ~/.bazel/bin by the time you get this error message.

**Comment by ncullen93** [comment]
No clue.. I think I do own ~/.cache/bazel, which is the weird part. Ah yes you're right that it is installed in ~/.bazel/bin, but running bazel still gives me the same error.

**Comment by kchodorow** [comment]
Create ~/.bazelrc that contains:

```
startup --output_base=/path/you/can/write/to
```

**Comment by yuqli** [comment]
I have the same problem and I have no idea why I don't own ~/.cache/bazel. I ran this command `sudo ./bazel-0.29.0-installer-linux-x86_64.sh --user`. After changing ownership of ~/.cache/bazel things worked.

**Comment by yuqli** [comment]
After changing privilege of this `~/.cache/bazel` to user, I later had problem in that I ran into permission issues using bazel in docker. So I had to change the permission again.
