### ISSUE TITLE
incompatible_use_toolchain_resolution_for_java_rules: use toolchain resolution for Java rules

### ISSUE THREAD

**Issue by lberki** [bazelbuild/bazel#7849]
**Flag:** `--incompatible_use_toolchain_resolution_for_java_rules`
**Available since:** 5.0.0
**Will be flipped in:** 5.0.0
**Tracking issue:** #4592

### **Motivation**

Currently, Java rules find their Java toolchain and JDK using the `--javabase` / `--java_toolchain` / `--host_javabase` / `--host_java_toolchain` command line options. This will be changed to use [platform-based toolchain resolution](https://docs.bazel.build/versions/master/toolchains.html) so as to be consistent with the rest of Bazel and to support multiple platforms more easily.

### **Migration notes**

For `--javabase` with old values: 
- `@local_jdk://jdk`
- `@remotejdk11_{linux,window,darwin}_{cpu}//:jdk`
- `@remotejdk14_{linux,window,darwin}//:jdk`
- `@remotejdk15_{linux,window,darwin}.*//:jdk`

Replace the flag with `--java_runtime_version={local_jdk,remotejdk_14,remotejdk_15}`. 

For `--java_toolchain` with old values: 
- `@bazel_tools//tools/jdk:toolchain`, 
- `@bazel_tools_hostjdk8`, 
- `@bazel_tools//jdk:legacy_toolchain`,
- `@bazel_tools//tools/jdk:remote_toolchain`,
- `@bazel_tools//tools/jdk:toolchain_java_{ver}`,
- `@remote_java_tools_xxx//:toolchain`,
- `@remote_java_tools_xxx//:toolchain_jdk_11`,
- `@remote_java_tools_xxx//:toolchain_jdk_14`,
- `@remote_java_tools_xxx//:toolchain_jdk_15`

Replace the flag with `--java_language_version={8,...,15}`

### **Migration of more advanced cases**

For `--javabase=@bazel_tools//tools/jdk:​absolute_javabase`, use `local_java_repositoy` in the `WORKSPACE` file.

For custom `--javabase` labels, do the following:
1. replace `http_archive` with `remote_java_repository`:

```py
remote_java_repository(
   name = ...
   sha256 = ...
   strip_prefix = ...
   urls = ...
   prefix = "myjdk",
   version = "11",
   exec_compatible_with = ["@platforms//cpu:arm", "@platforms//os:linux"]
)
```

2. replace the old flag with `--java_runtime_version` with the specified `version` or `prefix_version` value (for example `--java_runtime_version=myjdk_11`).

For old `--java_toolchain` values:
- `@bazel_tools//tools/jdk:toolchain_vanilla`
- `@remote_java_tools_xxx//:prebuilt_toolchain`
- custom label

1. add custom toolchain definition to a `BUILD` file (or replace custom target):
```py
default_java_toolchain(
  name = "mytoolchain",
  configuration = "PREBUILT_TOOLCHAIN_CONFIGURATION"
     #or "VANILLA_TOOLCHAIN_CONFIGURATION"
  ...
)
```
2. register custom toolchain in the `WORKSPACE` or use configuration flag `--extra_toolchains`.

### *RBE migration*

1. Update the version of bazel_toolchains.
2. Add following flags to `.bazelrc` affecting remote configuration:
```
build:remote --java_runtime_version=rbe_jdk     # Uses JDK installed on docker, configured by bazel_toolchains
build:remote --tool_java_runtime_version=rbe_jdk
build:remote --extra_toolchains=@rbe_ubuntu1804//java:all   # Optional: uses JDK installed on docker to compile 
```
3. In case the sources are not Java 8, also add:
```
build --java_language_version=11
build --tool_java_language_version=11
```
4. Once Bazel 4.1.0 is released and used on RBE Remove `--{,host}javabase` and `--{,host}_javatoolchain` flags.

**Comment by keith** [comment]
@lberki can you add migration notes for this? bazelisk's `--migrate` hits this and it appears that protobuf fails to build with this flag enabled with 0.25.2:

```
% bazel build :all --incompatible_use_toolchain_resolution_for_java_rules
INFO: Build option --incompatible_use_toolchain_resolution_for_java_rules has changed, discarding analysis cache.
ERROR: /Users/ksmiley/dev/protobuf/BUILD:636:1: in java_library rule //:protobuf_java: header compilation was requested but it is not supported by the current Java toolchain '@bazel_tools//tools/jdk:dummy_toolchain'; see the java_toolchain.header_compiler attribute
ERROR: Analysis of target '//:java_toolchain' failed; build aborted: Analysis of target '//:protobuf_java' failed; build aborted
INFO: Elapsed time: 0.604s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 2453 targets configured)
```

**Comment by laurentlb** [comment]
This flag breaks a lot of downstream projects, migration notes are missing, and the error message is unclear. I'm going to remove the migration flag for now.

**Comment by cushon** [comment]
> This flag breaks a lot of downstream projects, migration notes are missing, and the error message is unclear. I'm going to remove the migration flag for now.

There was some discussion of this in cl/240945826, and my understanding was that this met the policy requirements for adding an `--incompatible_*` flag. Has the policy changed?

I think the plan is still to add migration notes and push forward on this migration soon.

cc @iirina @hlopko

**Comment by hlopko** [comment]
Correct, we'll add migration instructions and start migrating soon. First we need to introduce Java constraint settings and values. @iirina is well on top of things.

**Comment by iirina** [comment]
The following  `java_toolchain` targets are exposed by Bazel: 
* `@bazel_tools//tools/jdk:toolchain`
* `@bazel_tools//tools/jdk:toolchain_hostjdk8`
* `@bazel_tools//tools/jdk:legacy_toolchain`
* `@bazel_tools//tools/jdk:toolchain_vanilla`
* `@bazel_tools//tools/jdk:toolchain_java{8, 9, 10, 11}`

Everyone using `--java_toolchain` pointing at any of these targets have to migrate. I'll come back with migration details for every of these targets.

**Comment by katre** [comment]
Removing the bazel 1.0 label and extending the migration window.

**Comment by iirina** [comment]
Yup, thanks!

**Comment by TomasPuverle** [comment]
Hi, is this and the associated PR dead?

**Comment by katre** [comment]
Assigning to @lberki to determine priority.

**Comment by pvcnt** [comment]
What is the status of this? It is really confusing right now, because docs seem to indicate we can use Java toolchains but since the PR is not merged this does not work. I would love to be able to use toolchains with Java rules!

**Comment by tp-github-config** [comment]
Any info would be very much appreciated!  Thank you.

**Comment by meisterT** [comment]
cc @comius

**Comment by davido** [comment]
@comius

On Bazel@HEAD (32fc451600b6e94a015263eb1c8a63e974f6f4cc)m after flipping of: `--incompatible_use_toolchain_resolution_for_java_rules` all `toolchain` parameters don#t have any affect. IOW, if I am using:

```
  $ bazel build \
  --java_toolchain=@bazel_tools//tools/jdk:toolchain_jdk_15 \
  --host_java_toolchain=@bazel_tools//tools/jdk:toolchain_jdk_15 \
  --javabase=@bazel_tools//tools/jdk:remotejdk_15 \
  --host_javabase=@bazel_tools//tools/jdk:remotejdk_15 \
  java/com/google/gerrit/common:server
Starting local Bazel server and connecting to it...
WARNING: Option 'java_toolchain' is deprecated
WARNING: Option 'host_java_toolchain' is deprecated
WARNING: Option 'javabase' is deprecated
WARNING: Option 'host_javabase' is deprecated
INFO: Invocation ID: dd6a4236-2ba0-49b2-8595-9ab4b043d6f7
DEBUG: /home/dos/.cache/bazel/_bazel_dos/f1d575400f8c6aeef34fcf7819876747/external/bazel_toolchains/rules/rbe_repo/version_check.bzl:59:14: 
Current running Bazel is not a release version and one was not defined explicitly in rbe_autoconfig target. Falling back to '3.1.0'
INFO: Analyzed target //java/com/google/gerrit/common:server (81 packages loaded, 3388 targets configured).
INFO: Found 1 target...
Target //java/com/google/gerrit/common:server up-to-date:
  bazel-bin/java/com/google/gerrit/common/libserver.jar
INFO: Elapsed time: 17.393s, Critical Path: 0.75s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
```

Then it works, but it doesn't produce Java major byte version 59:

```
  $ javap -v -cp bazel-bin/java/com/google/gerrit/common/libserver.jar \
  com.google.gerrit.common.data.Capable | grep major
  major version: 52
```

To make it work again, I have to explicitly specify: `--incompatible_use_toolchain_resolution_for_java_rules=false`, only then it works as expected:

```
  $ javap -v -cp bazel-bin/java/com/google/gerrit/common/libserver.jar \
  com.google.gerrit.common.data.Capable | grep major
  major version: 59
```

I would rather expect that `toolchain` options are not silently ignored, but rather rejected, us usually, right?

**Comment by comius** [comment]
> On Bazel@HEAD (32fc451), after flipping of: --incompatible_use_toolchain_resolution_for_java_rules all toolchain parameters don't seem to have any affect. IOW, if I am using (on Gerrit project):

This is expected. Flag has been flipped at head and old toolchain parameters don't have any effect unless you un-flip.

> I would rather expect that toolchain options are not silently ignored, but rather rejected, as usually, right?

This would potentially make transition less smooth. So if you're using two bazel versions, rejecting old flags would force you to upgrade bazel. Ignoring old flags makes it possible to have two sets of flags and thus support two versions of bazel at the same time.

Some warning might help, but new toolchains are designed to work without any flags... I don't know what could trigger the warning. (There will be something in release notes for sure).

**Comment by davido** [comment]
Thanks for clarification.

> This is expected.

That's very disruptive change. If users missed the release notes, they are screwed up. The build works, but produces wrong/unexpected results...

**Comment by comius** [comment]
> That's very disruptive change. If users missed the release notes, they are screwed up. The build works, but produces wrong/unexpected results...

This will be partially rectified on second rolling release and on LTS release as the old flags will be removed and builds will break.

**Comment by davido** [comment]
> This will be partially rectified on second rolling release and on LTS release as the old flags will be removed and builds will break.

**Bazel 4.0.0**: `--incompatible_use_toolchain_resolution_for_java_rules` is un-flipped, and the command: `bazel build java/com/google/gerrit/common:server` would produce (as expected) Java 11 byte code.

**Bazel 4.1.0**: `--incompatible_use_toolchain_resolution_for_java_rules` is flipped, and the command: `bazel build java/com/google/gerrit/common:server` would erroneously produce Java 8 byte code (and would break Gerrit project and all other Bazel users who rely on custom `toolchain` options).

**Bazel 5.0.0**: All old `toolchain` options will be dropped and users will be forced to migrate to `toolchain` resolution for java rules.

So the question is how we can avoid breakage in Bazel 4.1.0 (or whatever Bazel version will include that disruptive option flip). Note though, that the problem only exists if Bazel project is using custom `toolchain` options, like it's the case for Gerrit Code Review.

I see three options:

1. We skip Bazel 4.1.0 release entirely
2. We add `--incompatible_use_toolchain_resolution_for_java_rules=false` to `.bazelrc` during migration to Bazel 4.1.0
3. We switch immediately to toolchain resolution during migration to Bazel 4.1.0, and merge this CL: [1].

While thinking about it, why don't we provide one addition release, where "toolchain resolution for java rule feature" is available, but `incompatible_use_toolchain_resolution_for_java_rules` is not flipped?

Then the projects would have more time and non-disruptive migration path:

**Bazel 4.0.0**: "toolchain resolution for java rule feature" is not available
**Bazel 4.5.0**: "toolchain resolution for java rule feature" is available, but `--incompatible_use_toolchain_resolution_for_java_rules` is not flipped
**Bazel 4.7.0**: "toolchain resolution for java rule feature" is available, and `--incompatible_use_toolchain_resolution_for_java_rules` is flipped
**Bazel 5.0.0**: Old `toolchain` options are dropped

^^^ In the last scenario, we would migrate to 4.5.0 first (only bump `.bazelversion`) in the workspace and later (without breakage of final artifact), and only later switch to using "toolchain resolution for java rules" feature in: [1].

[1] https://gerrit-review.googlesource.com/c/gerrit/+/291864

**Comment by meisterT** [comment]
> > This will be partially rectified on second rolling release and on LTS release as the old flags will be removed and builds will break.
> 
> **Bazel 4.0.0**: `--incompatible_use_toolchain_resolution_for_java_rules` is un-flipped, and the command: `bazel build java/com/google/gerrit/common:server` would produce (as expected) Java 11 byte code.
> 
> **Bazel 4.1.0**: `--incompatible_use_toolchain_resolution_for_java_rules` is flipped, and the command: `bazel build java/com/google/gerrit/common:server` would erroneously produce Java 8 byte code (and would break Gerrit project and all other Bazel users who rely on custom `toolchain` options).

We should not enable incompatible flags in non major releases.

**Comment by davido** [comment]
> We should not enable incompatible flags in non major releases.

But it was flipped on Bazel@HEAD in c2485f67601cf7c79c5a49b29fb23194f7a7e9ab. So, whatever the next Bazel release would be, it would be included?

**Comment by meisterT** [comment]
cc @philwo 

Did you see the announcement here: https://blog.bazel.build/2020/11/10/long-term-support-release.html?

The incompatible change will be part of the rolling releases (that you can opt into but don't have to). The rolling release numbers will start with 5, the next major release.

The LTS track (currently the 4.0 branch) will only receive backwards compatible changes, most prominently bug fixes and security patches.

**Comment by davido** [comment]
Was it intentional that on Bazel@HEAD (ec7ecd74705ceadc064fd21aea6c04b0a0f749e4) this option cannot be unflipped any more?

Example from Gerrit@HEAD (ca87b681a0854801cbcdc67db4da3e940c7f1026)

```bash
  $ bazeldev build --incompatible_use_toolchain_resolution_for_java_rules=false
  ERROR: /home/davido/.cache/bazel/_bazel_davido/0fa756dec521553dbe2dde6b6eac99b4/external/com_google_protobuf/java/core/BUILD:95:13: in (an implicit dependency) attribute of java_library rule @com_google_protobuf//java/core:lite: '@bazel_tools//tools/jdk:current_java_toolchain' does not have mandatory providers: 'ToolchainInfo'. Since this rule was created by the macro 'java_library', the error might have been caused by the macro implementation
ERROR: Analysis of target '//src:bazel-bin-dev' failed; build aborted: Analysis of target '@com_google_protobuf//java/core:lite' failed
```

Also the description of this issue seems to be staled:

```
Will be flipped in: 4.1.0
```

This option wasn't flipped in 4.1.0rc1. And if I try to flip it manually, build doesn't seem to work any more:

```bash
  $ cat .bazelversion 
  4.1.0rc1

  $ bazelisk build --incompatible_use_toolchain_resolution_for_java_rules=true \
java/com/google/gerrit/common:server
  ERROR: /home/davido/.cache/bazel/_bazel_davido/5c01f4f713b675540b8b424c5c647f63/external/jgit/org.eclipse.jgit/BUILD:49:13: in java_library rule @jgit//org.eclipse.jgit:insecure_cipher_factory: header compilation was requested but it is not supported by the current Java toolchain '@bazel_tools//tools/jdk:dummy_toolchain'; see the java_toolchain.header_compiler attribute
ERROR: Analysis of target '//java/com/google/gerrit/common:server' failed; build aborted: Analysis of target '@jgit//org.eclipse.jgit:insecure_cipher_factory' failed
INFO: Elapsed time: 0.576s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 2716 targets configured)
```

**Comment by comius** [comment]
> Was it intentional that on Bazel@HEAD (ec7ecd7) this option cannot be unflipped any more?
No. @katre the error seems related to your recent commits.

> Also the description of this issue seems to be staled
Fixed it.

**Comment by katre** [comment]
I'll investigate the error.  @comius, should we add tests to cover this use-case?

**Comment by katre** [comment]
Yes, this is related to my changes to split ToolchainInfo out of JavaToolchainProvider and JavaRuntimeInfo's class hierarchy.

The good news is, I already have a change ready to fix this (see https://github.com/katre/bazel/tree/java-runtime-info).

The bad news is, I keep having to delay submitting it because I find more incorrect builds inside google.

I should be able to submit this week, however.

**Comment by davido** [comment]
@katre @comius 

Any progress here?

I still cannot build Gerrit on Bazel@HEAD, because I cannot unflip `--incompatible_use_toolchain_resolution_for_java_rules=false`.

I tried on: 6535847b7e166947feeeb2e378b5884b06b70a42:

```
  $ bazeldev build :headless
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
WARNING: Option 'java_toolchain' is deprecated
INFO: Invocation ID: a744562a-0965-47b2-9007-8107e00ea1ac
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=141
INFO: Reading rc options for 'build' from /home/davido/projects/gerrit2/.bazelrc:
  'build' options: --workspace_status_command=python ./tools/workspace_status.py --repository_cache=~/.gerritcodereview/bazel-cache/repository --action_env=PATH --disk_cache=~/.gerritcodereview/bazel-cache/cas --java_toolchain=//tools:error_prone_warnings_toolchain_java11 --incompatible_strict_action_env --announce_rc --experimental_worker_multiplex=false
INFO: Reading rc options for 'build' from /home/davido/.bazelrc:
  'build' options: --experimental_generate_json_trace_profile --experimental_profile_cpu_usage --incompatible_use_toolchain_resolution_for_java_rules=false
DEBUG: /home/davido/.cache/bazel/_bazel_davido/5c01f4f713b675540b8b424c5c647f63/external/bazel_toolchains/rules/rbe_repo/version_check.bzl:59:14: 
Current running Bazel is not a release version and one was not defined explicitly in rbe_autoconfig target. Falling back to '4.0.0'
ERROR: /home/davido/.cache/bazel/_bazel_davido/5c01f4f713b675540b8b424c5c647f63/external/bazel_tools/tools/jdk/BUILD:42:26: in :alias attribute of java_runtime_alias rule @bazel_tools//tools/jdk:legacy_current_java_runtime: '@bazel_tools//tools/jdk:remote_jdk11' does not have mandatory providers: 'ToolchainInfo'
ERROR: Analysis of target '//:headless' failed; build aborted: Analysis of target '@bazel_tools//tools/jdk:legacy_current_java_runtime' failed
INFO: Elapsed time: 13.082s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (109 packages loaded, 1279 targets configured)
    currently loading: @com_google_protobuf//
    Fetching @flogger; fetching
    Fetching @cafeteria; fetching
```

I also wrote this #12973: but it got P4 priority.

Bottom line: I cannot build Gerrit on Bazel@HEAD. The only workaround is to cherry-pick this issue: [1], that wasn't merged yet.

[1] https://gerrit-review.googlesource.com/c/gerrit/+/291864

**Comment by limdor** [comment]
Could someone add the label breaking-change-5.0? It would be slightly easier to find when searching for all Bazel 5.0 breaking changes

**Comment by comius** [comment]
> Could someone add the label breaking-change-5.0? It would be slightly easier to find when searching for all Bazel 5.0 breaking changes

Done.

**Comment by fmeum** [comment]
@lberki I think that this line in your migration notes:
```
Replace the flag with --java_runtime_version={localjdk,remotejdk_14,remotejdk_15}.
```
should be
```
Replace the flag with --java_runtime_version={local_jdk,remotejdk_14,remotejdk_15}.
```

Using `localjdk` instead of `local_jdk` results in no matching toolchain being found.

**Comment by comius** [comment]
> ```
> Replace the flag with --java_runtime_version={local_jdk,remotejdk_14,remotejdk_15}.
> ```
> 
> Using `localjdk` instead of `local_jdk` results in no matching toolchain being found.

Done, thanks @fmeum !

**Comment by shahms** [comment]
Some more detailed migration notes would be helpful. Following the steps outlined here all of the java_library targets fail with:
```
header compilation was requested but it is not supported by the current Java toolchain '@bazel_tools//tools/jdk:dummy_toolchain'; see the java_toolchain.header_compiler attribute
```
when using Bazel 4.2.0.

**Comment by shahms** [comment]
I had expected more breakage from updating to bazel 5.0.0 and wanted to try just that portion before tackling the rest, but aside from fighting with bazel-toolchains a bit, that was really all it took: https://github.com/kythe/kythe/pull/5205 :-)

**Comment by finn-ball** [comment]
This breaks for me when I upgraded one of my repositories and none of the fixes here worked.

Someone else has a reproducible example here which breaks for `bazel coverage`:
https://github.com/bazelbuild/bazel/issues/15035

**Comment by tayhargett8-rgb** [comment]
> **Flag:** `--incompatible_use_toolchain_resolution_for_java_rules` **Available since:** 5.0.0 **Will be flipped in:** 5.0.0 **Tracking issue:** [#4592](https://github.com/bazelbuild/bazel/issues/4592)
> 
> ### **Motivation**
> Currently, Java rules find their Java toolchain and JDK using the `--javabase` / `--java_toolchain` / `--host_javabase` / `--host_java_toolchain` command line options. This will be changed to use [platform-based toolchain resolution](https://docs.bazel.build/versions/master/toolchains.html) so as to be consistent with the rest of Bazel and to support multiple platforms more easily.
> 
> ### **Migration notes**
> For `--javabase` with old values:
> 
> * `@local_jdk://jdk`
> * `@remotejdk11_{linux,window,darwin}_{cpu}//:jdk`
> * `@remotejdk14_{linux,window,darwin}//:jdk`
> * `@remotejdk15_{linux,window,darwin}.*//:jdk`
> 
> Replace the flag with `--java_runtime_version={local_jdk,remotejdk_14,remotejdk_15}`.
> 
> For `--java_toolchain` with old values:
> 
> * `@bazel_tools//tools/jdk:toolchain`,
> * `@bazel_tools_hostjdk8`,
> * `@bazel_tools//jdk:legacy_toolchain`,
> * `@bazel_tools//tools/jdk:remote_toolchain`,
> * `@bazel_tools//tools/jdk:toolchain_java_{ver}`,
> * `@remote_java_tools_xxx//:toolchain`,
> * `@remote_java_tools_xxx//:toolchain_jdk_11`,
> * `@remote_java_tools_xxx//:toolchain_jdk_14`,
> * `@remote_java_tools_xxx//:toolchain_jdk_15`
> 
> Replace the flag with `--java_language_version={8,...,15}`
> 
> ### **Migration of more advanced cases**
> For `--javabase=@bazel_tools//tools/jdk:​absolute_javabase`, use `local_java_repositoy` in the `WORKSPACE` file.
> 
> For custom `--javabase` labels, do the following:
> 
> 1. replace `http_archive` with `remote_java_repository`:
> 
> remote_java_repository(
>    name = ...
>    sha256 = ...
>    strip_prefix = ...
>    urls = ...
>    prefix = "myjdk",
>    version = "11",
>    exec_compatible_with = ["@platforms//cpu:arm", "@platforms//os:linux"]
> )
> 2. replace the old flag with `--java_runtime_version` with the specified `version` or `prefix_version` value (for example `--java_runtime_version=myjdk_11`).
> 
> For old `--java_toolchain` values:
> 
> * `@bazel_tools//tools/jdk:toolchain_vanilla`
> * `@remote_java_tools_xxx//:prebuilt_toolchain`
> * custom label
> 
> 1. add custom toolchain definition to a `BUILD` file (or replace custom target):
> 
> default_java_toolchain(
>   name = "mytoolchain",
>   configuration = "PREBUILT_TOOLCHAIN_CONFIGURATION"
>      #or "VANILLA_TOOLCHAIN_CONFIGURATION"
>   ...
> )
> 2. register custom toolchain in the `WORKSPACE` or use configuration flag `--extra_toolchains`.
> 
> ### _RBE migration_
> 1. Update the version of bazel_toolchains.
> 2. Add following flags to `.bazelrc` affecting remote configuration:
> 
> ```
> build:remote --java_runtime_version=rbe_jdk     # Uses JDK installed on docker, configured by bazel_toolchains
> build:remote --tool_java_runtime_version=rbe_jdk
> build:remote --extra_toolchains=@rbe_ubuntu1804//java:all   # Optional: uses JDK installed on docker to compile 
> ```
> 
> 3. In case the sources are not Java 8, also add:
> 
> ```
> build --java_language_version=11
> build --tool_java_language_version=11
> ```
> 
> 4. Once Bazel 4.1.0 is released and used on RBE Remove `--{,host}javabase` and `--{,host}_javatoolchain` flags.
